### PR TITLE
DB-8846 changes in CDH-installation.md: Java Configuration Options for HBase Master (3.0)

### PR DESCRIPTION
**Pull request by martinrupp**
- classpath has to be added both for olapServer AND spark.executor.extraClassPath
- added -Dsplice.spark.submit.deployMode=client
- removed -XX:MaxPermSize=512M (obsolte)
- removed -Dsplice.spark.shuffle.compress=false
- removed -Dspark.compaction.reserved.slots=4
- -Dsplice.spark.master=yarn-client -> -Dsplice.spark.master=yarn
- changed

/opt/cloudera/parcels/SPARK2/lib/spark2/jars/
->
/opt/cloudera/parcels/CDH/lib/spark/jars/

### CODE REVIEW

**Comment by martinrupp** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED

**Comment by martinrupp** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
