### PR TITLE
SPLICE-2251 platform_it/pom.xml cleanup (2.7)

### PR DESCRIPTION
**Pull request by OlegMazurov**

### CODE REVIEW

**Comment by OlegMazurov** [comment]
jenkins please test branch @cdh5.12.2

**Comment by OlegMazurov** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by OlegMazurov** [comment]
jenkins please test branch @cdh5.13.3

**Comment by spliceci** [comment]
TEST FAILED

**Comment by OlegMazurov** [comment]
jenkins please test branch @cdh5.13.3

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
