### PR TITLE
DB-5592: Making HDP2.3.6 compile

### PR DESCRIPTION
**Pull request by scottfines**
This makes HDP-2.3.6 compile. I ran the ITs against it and a CDH branch to make sure there was no contamination, but it should be pretty clean

### CODE REVIEW

**Comment by ammolitor** [comment]
does this cause any issue with hdp2.4.2 compilation?

**Comment by scottfines** [comment]
I don't believe so, but I will confirm and adjust if necessary.

Thanks for the catch.

Scott

**Comment by scottfines** [comment]
HDP 2.4.2 compiles successfully. This isn't too much of a surprise--2.3.x and 2.4.x appear to run on different minor release versions of HBase (1.2.x versus 1.1.x), but it is good to double check

**Comment by ammolitor** [comment]
um, check your assumptions @scottfines, last I looked they are they are both using <envHbase>1.1.2</envHbase> and hence have the same code underneath.

**Comment by scottfines** [comment]
Well, I do get into trouble working from memory :)

**Comment by ammolitor** [comment]
well, your branch has this as I expected and so if they both compile here, then I am :+1:

**Comment by scottfines** [comment]
They don't. I don't know why, but it compiled and ran through ITs the first time through, but after your assumptions comment I re-checked, and it *is* showing problems. Will close this and re-open a new PR once I've resolved the issue.

**Pull request closed without merging**
