### PR TITLE
DB-10025 Fix issues that cause a full IT run to fail. (2.8)

### PR DESCRIPTION
**Pull request by msirek**
This Jira doesn't fix all of the test failures on 2.8.  There are a couple left, which can be fixed separately.
Here is a recent IT run with the fix on 2.8: 
http://nexus.splicemachine.com:8080/job/spliceengine-branch/job/spliceengine-branch/1906/

### CODE REVIEW

**Comment by msirek** [comment]
jenkins please test branch @cdh5.12.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1360/

**Comment by msirek** [comment]
jenkins please test branch @cdh5.16.1,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1377/

**Pull request merged**
