### PR TITLE
DB-9911 use Spark ORC reader instead of Presto ORC reader

### PR DESCRIPTION
**Pull request by martinrupp**

### CODE REVIEW

**Comment by martinrupp** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Review by dgomezferro — APPROVED** [review]

**Comment by dgomezferro** [comment]
@martinrupp doesn't the `skipTestsLongerThan2Minutes` flag skip external table tests? I think we should run a full build here.

**Review by ipraznik-splice — APPROVED** [review]

**Comment by martinrupp** [comment]
> @martinrupp doesn't the `skipTestsLongerThan2Minutes` flag skip external table tests? I think we should run a full build here.

ExternalTableIT is not marked with LongerThanTwoMinutes. But ExternalTablePartitionIT is, so we can also run a full test here, you're right

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1791/

**Review by bklo94 — APPROVED** [review]

**Review by carolp-503 — APPROVED** [review]
+1

**Pull request merged**
