### PR TITLE
DB-7702 Rename splice_spark artifactId to reflect module

### PR DESCRIPTION
**Pull request by bklo94**

### CODE REVIEW

**Comment by bklo94** [comment]
jenkins please test branch @cdh5.13.3

**Comment by spliceci** [comment]
TEST FAILED - GitHub pull request #2493 of commit dc5f736f30d1c968c6ddd9a4102d6e4202779feb, no merge conflicts.

**Comment by bklo94** [comment]
jenkins please test branch

**Comment by bklo94** [comment]
jenkins please test branch @cdh5.13.3

**Pull request merged**
