### PR TITLE
DB-10882 Support updatable cursors

### PR DESCRIPTION
**Pull request by hatyo**

### CODE REVIEW

**Comment by hatyo** [comment]
jenkins please test branch @cdh6.3.0

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2195/

**Comment by hatyo** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by dgomezferro — APPROVED** [review]

**Review by ipraznik-splice — APPROVED** [review]

**Review by carolp-503 — COMMENTED** [review]
+1

**Review by carolp-503 — APPROVED** [review]

**Pull request merged**
