### PR TITLE
DB-10899 Throw in getKeyColumnPosition() for index on expressions

### PR DESCRIPTION
**Pull request by ascend1**

### CODE REVIEW

**Comment by ascend1** [comment]
jenkins please test branch @cdh6.3.0

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by martinrupp — CHANGES_REQUESTED** [review]
please add a small test for this

**Review by arnaud-splice — APPROVED** [review]
+1 once Martin's comment is addressed

**Review by ipraznik-splice — APPROVED** [review]

**Review by martinrupp — APPROVED** [review]

**Comment by ascend1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by ascend1** [comment]
> please add a small test for this

Done.

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by carolp-503 — APPROVED** [review]
+1

**Pull request merged**
