### PR TITLE
DB-6905 Increase DECIMAL precision to 38 digits.

### PR DESCRIPTION
**Pull request by msirek**
Increase the maximum decimal precision supported by Splice from 31 to 38 digits.
Note that this feature will require the use of a new JDBC driver or sqlshell client for reading DECIMAL38 data.

I have pushed a commit to update the implicit casting rules for arithmetic operations such that they only cast to a max precision of 31 if the connection is from an old JDBC or sqlshell client that only supports DECIMAL31.

See [DB-6905](https://splicemachine.atlassian.net/browse/DB-6905) for more info.

### CODE REVIEW

**Comment by msirek** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST FAILED

**Comment by msirek** [comment]
jenkins please test branch @cdh5.12.2

**Comment by msirek** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST FAILED

**Comment by msirek** [comment]
jenkins please test branch @cdh5.13.3

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
