### PR TITLE
DB-11176 Remove cdh/hdp repository from pom.xml (3.0)

### PR DESCRIPTION
**Pull request by bklo94**

### CODE REVIEW

**Comment by bklo94** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by cloudspliceci** [comment]
TRY AGAIN

**Comment by bklo94** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by bklo94** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by cloudspliceci** [comment]
TRY AGAIN

**Comment by cloudspliceci** [comment]
TRY AGAIN

**Comment by bklo94** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by cloudspliceci** [comment]
TRY AGAIN

**Comment by bklo94** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by cloudspliceci** [comment]
TEST FAILED
https://jenkins.build.splicemachine-dev.io/job/AutomatedTesting/job/spliceengine-PR/99/

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by carolp-503 — APPROVED** [review]
Approved for 3.0

**Pull request merged**
