### PR TITLE
SPLICE-1575 ValueRow.hashCode() value should be cached

### PR DESCRIPTION
**Pull request by OlegMazurov**
Cache hashCode() value for ValueRow. Invalidate on any change to the object. Include in serde.

### CODE REVIEW

**Comment by jleach4** [comment]
It will be interesting to see if this works...  @dgomezferro is there any set by reference items in the activation that would bypass this?

**Comment by dgomezferro** [comment]
@jleach4 I don't think so, although it is a risk. AFAIK we only use the .hashcode() in ValueRows that act as "keys", and we shouldn't be modifying those. I'm OK with merging and fixing any issues that may come up.

**Comment by jleach4** [comment]
+1 and lets see how it shakes out.

**Comment by dgomezferro** [comment]
@OlegMazurov could we get a run on jenkins prior to merging?

**Pull request merged**
