### PR TITLE
DB-6376 Allow importing more than one JAR in a schema

### PR DESCRIPTION
**Pull request by changli6**

### CODE REVIEW

**Comment by changli6** [comment]
jenkins please test branch @cdh6.3.0

**Comment by spliceci** [comment]
TEST FAILED

**Comment by changli6** [comment]
> This needs an upgrade script to remove the index on existing databases.
Thanks @dgomezferro to point it. Added the upgrade script.

**Comment by changli6** [comment]
jenkins please test branch @cdh6.3.0

**Comment by spliceci** [comment]
TEST FAILED

**Pull request merged**
