### PR TITLE
Add snappy compression in DRDA layer (server side)

### PR DESCRIPTION
**Pull request by snowspeeder**
odbc server side snappy changes from server side.

### CODE REVIEW

**Comment by jyuanca** [comment]
One question: where the data gets decompressed?

**Comment by snowspeeder** [comment]
in the odbc driver which is another pull request

**Comment by scottfines** [comment]
What about the JDBC side?

**Comment by snowspeeder** [comment]
it is right now for odbc improvements, jdbc was not the focus, may be later
we can add that too.

**Comment by genedavis** [comment]
+1

**Comment by jleach4** [comment]
+1

**Comment by jleach4** [comment]
Can we get this in?

**Comment by snowspeeder** [comment]
yep, its on my radar for this week merge, I wanted to get all external
table issues in first due to priority.

**Comment by jleach4** [comment]
Makes sense…

I am close to getting a patch in that will speed up our ITs.  It is a bit rough right now.

John

**Pull request merged**
