### PR TITLE
DB-8195 Calculate average split size for the splits=n hint.

### PR DESCRIPTION
**Pull request by msirek**
This JIRA fixes uneven splits when region sizes are imbalanced.

See [DB-8195](https://splicemachine.atlassian.net/browse/DB-8195).

### CODE REVIEW

**Comment by msirek** [comment]
jenkins please test branch @cdh5.12.2

**Comment by jaceklaskowski** [comment]
Why testing on `cdh5.12.2`? Is this the default profile? Trying to learn a bit about the profiles and hence the question.

**Comment by msirek** [comment]
Hi @jaceklaskowski, cdh5.12.2 is just a version commonly installed on some of our clusters, so I tend to use this, but you can run tests against any of the supported platforms found in the pom file.

**Comment by msirek** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST FAILED

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by msirek** [comment]
jenkins please test branch @mem

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by msirek** [comment]
@yxia92  I found overhead is coming from this code:

    public SMRecordReaderImpl getRecordReader(InputSplit split, Configuration config) throws IOException,
            InterruptedException {
        config.addResource(conf);
        **if (LOG.isDebugEnabled())
            SpliceLogUtils.debug(LOG, "getRecordReader with table=%s, inputTable=%s," +
                    "conglomerate=%s",
                    table,
                    config.get(TableInputFormat.INPUT_TABLE),
                    config.get(MRConstants.SPLICE_INPUT_CONGLOMERATE));**

I don't know the exact cause of the overhead.  Sometimes logging itself has some overhead.  This will only affect running standalone, where DEBUG is turned on.  Platform builds (e.g. parcels) don't have this turned on by default.

**Comment by yxia92** [comment]
I see, thanks!

**Comment by msirek** [comment]
@dgomezferro I removed the record reader and now use HBaseRegionLoads.tableLoad(), which uses RegionSizeEndpoint.computeRegionSize() to get Store sizes in parallel.  It also caches the result so it doesn't have to be recomputed each time.

**Comment by msirek** [comment]
jenkins please test branch @cdh5.13.3

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
