### PR TITLE
DB-12283 Use UUIDs as session IDs instead of lcc.getInstanceNumber() (3.1)

### PR DESCRIPTION
**Pull request by ascend1**
See https://github.com/splicemachine/spliceengine/pull/5630.

### CODE REVIEW

**Comment by ascend1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by ascend1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by cloudspliceci** [comment]
TEST SUCCEEDED +1

**Comment by cloudspliceci** [comment]
TEST SUCCEEDED +1

**Comment by ascend1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by cloudspliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/3318/

**Comment by ascend1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by cloudspliceci** [comment]
TEST SUCCEEDED +1

**Review by carolp-503 — APPROVED** [review]
Approved for 3.1

**Pull request merged**
