### PR TITLE
DB-8290 Update from a subquery does not update null columns in PK tables.

### PR DESCRIPTION
**Pull request by msirek**
This fixes MERGE_DATA_FROM_FILE when there are nulls in the target table.
MERGE_DATA_FROM_FILE uses:
> UPDATE _tab_name_ SET _col_name_ = (_subquery_)

... internally, so this DML encounters the bug as well.

See [DB-8290](https://splicemachine.atlassian.net/browse/DB-8290)

### CODE REVIEW

**Comment by msirek** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
Job Failure
 
TEST FAILED

**Comment by spliceci** [comment]
TEST FAILED

**Comment by msirek** [comment]
jenkins please test branch @cdh5.13.3

**Comment by spliceci** [comment]
Job Failure
 
TEST FAILED

**Comment by spliceci** [comment]
TEST FAILED

**Comment by msirek** [comment]
jenkins please test branch @cdh5.13.3

**Comment by spliceci** [comment]
Job Success
 
TEST SUCCEEDED +1

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
