### PR TITLE
DB-11211 support multi-column VTI in subquery.

### PR DESCRIPTION
**Pull request by hatyo**
In this PR we support multi-column VTI in subquery, if possible, the subquery will be flattened.

Previously, running this example would've thrown an NPE:

```
create table D(a1 int, a2 varchar(3));
create view VT as select * from 
new com.splicemachine.derby.vti.SpliceFileVTI('<SOME CSV FILE>','',',') 
AS x(b1 int, b2 varchar(3));
-- add some data to both table D
select a1,a2 from D WHERE (a1,a2) in (select b1,b2 from VT) order by a1; -- NPE
```

Now it works, e.g.:
```

select a1,a2 from D WHERE (a1,a2) in (select b1,b2 from VT) order by a1;
A1 |A2  |
---------
1 |x11 |
1 |x14 |
2 |x22 |
```

### CODE REVIEW

**Comment by hatyo** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2506/

**Comment by hatyo** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2510/

**Comment by hatyo** [comment]
Failed IT is irrelevant to this PR and it is also failing in /master.

**Review by ipraznik-splice — APPROVED** [review]

**Review by martinrupp — APPROVED** [review]

**Comment by hatyo** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2520/

**Review by carolp-503 — APPROVED** [review]
+1

**Comment by hatyo** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by hatyo** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by ascend1 — APPROVED** [review]

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by msirek — APPROVED** [review]

**Pull request merged**
