### PR TITLE
DB-10599 check column nullability with foreign key set null.

### PR DESCRIPTION
**Pull request by hatyo**
In this PR we prevent `set null` action from setting any not-nullable foreign key column to `null` as this breaks the not-null constraint of such columns.

Moreover, a similar error propagation mechanism to foreign key violation is extended to cover this case as well such that we could cancel the entire lineage of foreign key effects if such violation occurs.

### CODE REVIEW

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Review by arnaud-splice — APPROVED** [review]
+1

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1911/

**Review by msirek — APPROVED** [review]

**Comment by hatyo** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1923/

**Comment by hatyo** [comment]
e2e tests failed because of DB-10721.

**Review by dgomezferro — APPROVED** [review]

**Pull request merged**
