### PR TITLE
DB-10228 Improve metadata queries' performance

### PR DESCRIPTION
**Pull request by ascend1**
- getTables query: show tables/views/synonyms/aliases [in ...]
- getColumns query: describe ...
- getIndexInfo query: show indexes ...
- getPrimaryKeys query: show primarykeys ...

### CODE REVIEW

**Review by dgomezferro — CHANGES_REQUESTED** [review]
Change looks good @ascend1 , great speedups! 

I think this won't trigger a recompilation of the metadata queries on upgrade though, can you verify? If not can you add an upgrade script that calls `SYSCS_UPDATE_METADATA_STORED_STATEMENTS()` or equivalent (`DataDictionary.updateMetadataSPSes()`) ? Thanks!

**Comment by ascend1** [comment]
> Change looks good @ascend1 , great speedups!
> 
> I think this won't trigger a recompilation of the metadata queries on upgrade though, can you verify? If not can you add an upgrade script that calls `SYSCS_UPDATE_METADATA_STORED_STATEMENTS()` or equivalent (`DataDictionary.updateMetadataSPSes()`) ? Thanks!

Right, I forget to add the upgrade script. I found this issue locally when moving between test environments, but still ...Thanks!

**Comment by ascend1** [comment]
> Change looks good @ascend1 , great speedups!
> 
> I think this won't trigger a recompilation of the metadata queries on upgrade though, can you verify? If not can you add an upgrade script that calls `SYSCS_UPDATE_METADATA_STORED_STATEMENTS()` or equivalent (`DataDictionary.updateMetadataSPSes()`) ? Thanks!

Right, I think `sdd.updateMetadataSPSes(tc)` is always called in doing an upgrade. This is in SpliceCatalogUpgradeScripts, run() method.

**Comment by ascend1** [comment]
Just verified locally, that SPSes are updated in an upgrade (1987 (old SPSes) -> 1988 (new SPSes on DB-10228)).

**Review by dgomezferro — APPROVED** [review]

**Review by msirek — APPROVED** [review]

**Review by carolp-503 — APPROVED** [review]
+1

**Comment by jpanko1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2038/

**Comment by ascend1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
