### PR TITLE
DB-11238 Promote NLJ+IndexLookup+IndexScan on OLTP and optimizer bug fixes

### PR DESCRIPTION
**Pull request by ascend1**
This change includes three optimizer bug fixes and one tuning on cost model. A detailed explanation is here: https://splicemachine.atlassian.net/browse/DB-11238?focusedCommentId=73828

Note that this change doesn't solve the problem of choosing between OLTP and OLAP completely. WIth this change, slow queries reported in the Jira ticket run faster. They should get improved plans if we have better statistics. However, this is more about a different issue.

### CODE REVIEW

**Comment by ascend1** [comment]
jenkins please test branch @cdh6.3.0

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2393/

**Comment by ascend1** [comment]
jenkins please test branch @cdh6.3.0

**Comment by ascend1** [comment]
jenkins please test branch @cdh6.3.0

**Comment by ascend1** [comment]
jenkins please test branch @cdh6.3.0

**Review by dgomezferro — APPROVED** [review]

**Review by ipraznik-splice — APPROVED** [review]

**Review by msirek — APPROVED** [review]
@ascend1 Nice job!  A lot of great fixes here.

**Review by carolp-503 — APPROVED** [review]
+1

**Comment by genedavis** [comment]
What's with the magic number of "divide by 10"? on lookupCostPerRow?  Should this be parameterized?

**Pull request merged**
