### PR TITLE
DB-10378 Fix duplication check for expression-based indexes

### PR DESCRIPTION
**Pull request by ascend1**

### CODE REVIEW

**Comment by ascend1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by jyuanca — APPROVED** [review]

**Review by yxia92 — APPROVED** [review]
+1

**Review by carolp-503 — APPROVED** [review]
+1

**Pull request merged**
