### PR TITLE
DB-6047: create child persistent node to avoid ZOOKEEPER-2052

### PR DESCRIPTION
**Pull request by jyuanca**

### CODE REVIEW

**Comment by dgomezferro** [comment]
@jyuanca  This change could leave persistent znodes blocking flushes after a restart, is that prevented somehow?

**Comment by jyuanca** [comment]
@dgomezferro There is a timestamp in the root node for backup, which Backup updates periodically when it is active. The flushing thread can check the timestamp for timeout.

**Comment by dgomezferro** [comment]
@jyuanca is that check implemented already?

**Comment by jyuanca** [comment]
@dgomezferro Yes, it is checked in already.

**Comment by dgomezferro** [comment]
@jyuanca cool, thanks!

**Pull request merged**
