### PR TITLE
DB-8957 Not Equals Operators ^= Verification

### PR DESCRIPTION
**Pull request by changli6**
This PR is for testing ^= operator (DB-8931) on different data types.

### CODE REVIEW

**Comment by changli6** [comment]
Jenkins please branch @cdh5.12.2

**Comment by changli6** [comment]
Jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST FAILED

**Comment by changli6** [comment]
Jenkins please test branch @mem

**Comment by spliceci** [comment]
TEST FAILED

**Comment by changli6** [comment]
Jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
