### PR TITLE
DB-11117 NPE in getPreserveLineEndings/SpliceFileVTI

### PR DESCRIPTION
**Pull request by OlegMazurov**
Create a delegating ContextManager. No need to push LCC using initCurrentLCC() (will be available from the parent ContextManager). Cleanup must be done on the same thread. Newly created ContextManager must be destroyed.
I'm also fixing memory leak warnings in ContextService.

### CODE REVIEW

**Comment by martinrupp** [comment]
looks good to me, and works with the test testPropertiesCacheNPE. i checked on master+mem, there testPropertiesCacheNPE fails, on DB-11117+mem it succeeds, so this should be good!

**Comment by martinrupp** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2222/

**Review by dgomezferro — APPROVED** [review]

**Comment by martinrupp** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2223/

**Comment by martinrupp** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Review by martinrupp — APPROVED** [review]

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2224/

**Review by jyuanca — APPROVED** [review]

**Pull request merged**
