### PR TITLE
Redo "DB-10067 Support creating indexes on expressions"

### PR DESCRIPTION
**Pull request by ascend1**
This reverts commit 32991b702587aaec0c59fb8868e943627ad9b0f5.

### CODE REVIEW

**Comment by ascend1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1568/

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1569/

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by martinrupp — APPROVED** [review]

**Review by arnaud-splice — APPROVED** [review]

**Pull request merged**
