### PR TITLE
DB-10488 ExternalTable insert row counts not correct on 2.8

### PR DESCRIPTION
**Pull request by martinrupp**

### CODE REVIEW

**Comment by martinrupp** [comment]
jenkins please test branch @cdh5.12.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1693/

**Review by arnaud-splice — APPROVED** [review]

**Review by dgomezferro — APPROVED** [review]

**Review by carolp-503 — APPROVED** [review]
Approved for 2.8

**Comment by martinrupp** [comment]
jenkins please test branch @cdh5.12.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
