### PR TITLE
[DRAFT] DB-10961 Get rid of the NodeFactory part 3

### PR DESCRIPTION
**Pull request by martinrupp**
iterative PR to get rid of NodeFactory / getNode

### CODE REVIEW

**Comment by martinrupp** [comment]
jenkins please test branch @cdh6.3.0

**Comment by martinrupp** [comment]
failed
```
com.splicemachine.db.impl.sql.compile.ProjectionPruningIT.testSetOperation[0]
com.splicemachine.db.impl.sql.compile.ProjectionPruningIT.testSetOperation[1]
com.splicemachine.derby.impl.sql.execute.operations.AnyOperationIT.testNonCorrelatedSubqueryWithExcept
com.splicemachine.derby.impl.sql.execute.operations.CachedOperationIT.testCacheDistinctScan
com.splicemachine.derby.impl.sql.execute.operations.GeneratedColumnIT.testCanInsertGeneratedDataWithIncrement
com.splicemachine.derby.impl.sql.execute.operations.GeneratedColumnIT.testCanInsertDefaultGeneratedData
com.splicemachine.derby.impl.sql.execute.operations.GeneratedColumnIT.testCanInsertGeneratedDataStartingWithValue
com.splicemachine.derby.impl.sql.execute.operations.GeneratedColumnIT.com.splicemachine.derby.impl.sql.execute.operations.GeneratedColumnIT
com.splicemachine.derby.impl.sql.execute.operations.InsertOperationIT.testInsertDefaultsNull
com.splicemachine.derby.impl.sql.execute.operations.UnionOperationIT.testUnionValuesInSubSelect
com.splicemachine.derby.impl.sql.execute.operations.UnionOperationIT.testUnionMaterializedSubquery
com.splicemachine.derby.impl.sql.execute.operations.joins.NestedLoopJoinOperationIT.testNLJWithRightTableContainsSubquery
com.splicemachine.foreignkeys.ForeignKeyMetadataIT.testSQLFOREIGNKEYSReturnsCorrectForImportedKeys
com.splicemachine.foreignkeys.ForeignKeyMetadataIT.testSQLFOREIGNKEYSReturnsCorrectForExportedKeys
com.splicemachine.subquery.Subquery_Flattening_InList_IT.testSetOpInSubQFlatten
com.splicemachine.subquery.Subquery_Flattening_Values_IT.valuesThrows
com.splicemachine.subquery.Subquery_Scalar_IT.scalarSubqueryExpected
com.splicemachine.subquery.Subquery_Table_IT.inWeirdQuery
```

**Comment by martinrupp** [comment]
Java exception: 'java.lang.RuntimeException: java.lang.InstantiationException: com.splicemachine.db.impl.sql.compile.SubqueryNode

**Comment by martinrupp** [comment]
com.splicemachine.derby.impl.sql.execute.operations.InsertOperationIT.testInsertDefaultsNull
Java exception: 'java.lang.ClassCastException: com.splicemachine.db.impl.sql.compile.RowResultSetNode cannot be cast to com.splicemachine.db.impl.sql.compile.FromBaseTable'.

**Comment by martinrupp** [comment]
jenkins please test branch @cdh6.3.0

**Comment by martinrupp** [comment]
May 18 commits are from `DB-10961 Get rid of the NodeFactory part 2 #5483`

**Comment by martinrupp** [comment]
mvn clean install -Pcdh6.3.0,core -DskipTests

**Comment by martinrupp** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by cloudspliceci** [comment]
TEST SUCCEEDED +1

**Pull request closed without merging**
