### PR TITLE
DB-11343 Fix ForeignKeyCheckIT caused by DB-10756

### PR DESCRIPTION
**Pull request by ipraznik-splice**

### CODE REVIEW

**Review by dgomezferro — APPROVED** [review]

**Comment by ipraznik-splice** [comment]
jenkins please test branch @cdh6.3.0

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2399/

**Comment by ipraznik-splice** [comment]
jenkins please test branch @mem

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2400/

**Review by jpanko1 — APPROVED** [review]

**Pull request merged**
