### PR TITLE
DB-8138 Fix row triggers when UPDATE row and TRIGGER row have differe…

### PR DESCRIPTION
**Pull request by msirek**
…nt column counts.

### CODE REVIEW

**Comment by msirek** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST FAILED

**Comment by msirek** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by msirek** [comment]
Done with experimental fix.

**Pull request closed without merging**
