### PR TITLE
Test jenkins bot webhook

### PR DESCRIPTION
**Pull request by bklo94**
Please don't merge. Testing jenkins bot PR webhook

### CODE REVIEW

**Comment by bklo94** [comment]
jenkinsbot please test @cdh6.3.0

**Comment by bklo94** [comment]
jenkinsbot please test @cdh6.3.0

**Comment by bklo94** [comment]
bot please test @cdh6.3.0

**Comment by bklo94** [comment]
bot please test @cdh6.3.0

**Comment by bklo94** [comment]
bot please test @cdh6.3.0

**Comment by cloudspliceci** [comment]
TEST FAILED
https://jenkins.build.splicemachine-dev.io/job/AutomatedTesting/job/spliceengine-PR/168/

**Comment by bklo94** [comment]
bot please test @cdh6.3.0

**Comment by bklo94** [comment]
bot please test @hdp3.1.5

**Comment by bklo94** [comment]
bot please test @dbaas3.0

**Comment by cloudspliceci** [comment]
TEST FAILED
https://jenkins.build.splicemachine-dev.io/job/AutomatedTesting/job/spliceengine-PR/171/

**Comment by cloudspliceci** [comment]
TEST FAILED
https://jenkins.build.splicemachine-dev.io/job/AutomatedTesting/job/spliceengine-PR/170/

**Comment by bklo94** [comment]
bot please test @cdh6.3.0

**Comment by bklo94** [comment]
bot please test @hdp3.1.5

**Comment by bklo94** [comment]
bot please test @dbaas3.0

**Comment by cloudspliceci** [comment]
TEST FAILED
https://jenkins.build.splicemachine-dev.io/job/AutomatedTesting/job/spliceengine-PR/174/

**Comment by cloudspliceci** [comment]
TEST FAILED
https://jenkins.build.splicemachine-dev.io/job/AutomatedTesting/job/spliceengine-PR/172/

**Comment by cloudspliceci** [comment]
TEST FAILED
https://jenkins.build.splicemachine-dev.io/job/AutomatedTesting/job/spliceengine-PR/173/

**Comment by cloudspliceci** [comment]
TEST FAILED
https://jenkins.build.splicemachine-dev.io/job/AutomatedTesting/job/spliceengine-PR/169/

**Comment by bklo94** [comment]
bot please test @dbaas3.0

**Comment by bklo94** [comment]
jenkins please test @dbaas3.0

**Comment by bklo94** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by cloudspliceci** [comment]
TEST FAILED
https://jenkins.build.splicemachine-dev.io/job/AutomatedTesting/job/spliceengine-PR/175/

**Comment by cloudspliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/3211/

**Comment by bklo94** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by cloudspliceci** [comment]
TEST FAILED
https://jenkins.build.splicemachine-dev.io/job/AutomatedTesting/job/spliceengine-PR/176/

**Comment by cloudspliceci** [comment]
TEST SUCCEEDED +1

**Pull request closed without merging**
