### PR TITLE
SPLICE-1478 Fixing Statement Limits

### PR DESCRIPTION
**Pull request by jleach4**
Allows for statements to be larger than utf serde bounds.

### CODE REVIEW

**Comment by dgomezferro** [comment]
@jleach4 no 2.0 backport?

**Comment by jleach4** [comment]
hmm, did not give 2.0 any love did I...  

Will crank one out when I get into the office.  Good catch.

**Comment by jleach4** [comment]
Pull request created...

**Comment by genedavis** [comment]
+1

**Pull request merged**
