### PR TITLE
DB-7732: fix clob regression(2.5)

### PR DESCRIPTION
**Pull request by jyuanca**

### CODE REVIEW

**Comment by jyuanca** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST FAILED

**Comment by MurrayBrown** [comment]
jenkins please retest branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST FAILED

**Comment by jyuanca** [comment]
Test failed because ranger has dependency on mem_sql jar. It should not fail jenkins build once it's merged

**Pull request merged**
