### PR TITLE
DB-10494 DDL coordination timed out when analyze schema with many tables

### PR DESCRIPTION
**Pull request by ipraznik-splice**
## Short Description
ddl notifications are partitioned during COLLECT_SCHEMA_STATISTICS. Previously, a large list of table descriptor ids was sent in one call. 

## Long Description
When COLLECT_SCHEMA_STATISTICS analyzes a big schema with many tables, it could cause a DDL coordination timeout. The problem happens when the massage with ddlChangeType: ALTER_STATS has many table descriptor ids. To avoid this issue, the new method ddlNotificationInPartitions splits the list of table descriptors into smaller partitions with the size given in partitionSize.

## How to test
Create a schema with big amount of tables, some thousands, and call  COLLECT_SCHEMA_STATISTICS. It's also possible to decrease the environment variable splice.ddl.maxWaitSeconds to have a higher probability to get a timeout.

### CODE REVIEW

**Comment by ipraznik-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by jyuanca — APPROVED** [review]

**Review by dgomezferro — APPROVED** [review]

**Comment by ipraznik-splice** [comment]
> @ipraznik-splice can you coordinate with QA to add a regression test for this?
sure, will add info to qa-reception channel

**Review by arnaud-splice — APPROVED** [review]

**Review by carolp-503 — APPROVED** [review]
+1

**Pull request merged**
