### PR TITLE
DB-10890 fix DESCRIBE table returning non-related columns.

### PR DESCRIPTION
**Pull request by hatyo**
This PR fixes `DESCRIBE [PROCEDURE]` client-statement returning columns that belong to unrelated tables, the reason why this was happening is that `DESCRIBE` is translated under the hood into a `DatabaseMetadata.getColumns` API call, this call expects pattern arguments (a pattern is a string with `LIKE` placeholders `_` and `%`), if the table name contains such placeholders the `getColumns` will interpret it as a pattern potentially returning columns from other tables that match the given pattern.

To fix this, we escape the `DESCRIBE` arguments using an escape character that is also introduced to each `LIKE` predicate in the underlying `getColumns`'s (resp. `getProcedureColumns`) SQL statement. 

Moreover, all metadata queries (in `metadata.properties`) are adapted such that `LIKE` operators now have `ESCAPE '\'`, the JDBC API `getSearchStringEscape` now also returns `\`.

### CODE REVIEW

**Comment by ascend1** [comment]
jenkins please test branch @cdh6.3.0

**Review by ascend1 — APPROVED** [review]
Nice change!

**Review by arnaud-splice — APPROVED** [review]

**Review by martinrupp — APPROVED** [review]
nice!

**Review by dgomezferro — CHANGES_REQUESTED** [review]
@hatyo is going to adapt other metadata queries too, leaving this here to prevent early merging.

**Comment by hatyo** [comment]
> @hatyo is going to adapt other metadata queries too, leaving this here to prevent early merging.

Yes @dgomezferro I wanted to do that in a separate JIRA but considering how closely related this ticket is, I will do it here. Will push a new commit addressing that.

**Comment by hatyo** [comment]
jenkins please test branch @cdh6.3.0

**Comment by hatyo** [comment]
jenkins please test branch @cdh6.3.0

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2059/

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2063/

**Comment by jpanko1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2069/

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2074/

**Comment by jpanko1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2075/

**Comment by hatyo** [comment]
Following test failed `com.splicemachine.derby.utils.StatisticsAdminIT.testTableStatisticsCorrectForOccupiedTable`, should've been fixed in the latest master so I merged master. Let's try again.

**Comment by hatyo** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by dgomezferro — APPROVED** [review]

**Review by carolp-503 — APPROVED** [review]
+1

**Pull request merged**
