### PR TITLE
DB-9502 Run FLUSH as part of MAJOR_COMPACTION

### PR DESCRIPTION
**Pull request by ipraznik-splice**
# Short Description
Calls flush before major compaction

# Long Description
in the method SYSCS_PERFORM_MAJOR_COMPACTION_ON_TABLE partition.flush() is called before partition.compact(true)

# How to test
execute CALL SYSCS_UTIL.SYSCS_PERFORM_MAJOR_COMPACTION_ON_TABLE([SCHEMA_NAME]); in sqlshel and check, that compaction is executed and no errors.

### CODE REVIEW

**Review by jpanko1 — APPROVED** [review]

**Review by msirek — APPROVED** [review]

**Comment by hatyo** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2507/

**Comment by ipraznik-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2508/

**Review by jyuanca — APPROVED** [review]

**Comment by ipraznik-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by carolp-503 — APPROVED** [review]
+1

**Pull request merged**
