### PR TITLE
DB-10686 do not remove inlist condition after being processed in code…

### PR DESCRIPTION
**Pull request by yxia92**
… generation phase as code generation for the same tree could happen twice

### CODE REVIEW

**Comment by yxia92** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by jyuanca — APPROVED** [review]

**Review by arnaud-splice — APPROVED** [review]

**Comment by yxia92** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by dgomezferro — APPROVED** [review]
I've tested this fix with DB-10706 test case and it also fixes it, thanks @yxia92 !

**Review by arnaud-splice — APPROVED** [review]

**Review by jyuanca — APPROVED** [review]

**Review by carolp-503 — APPROVED** [review]
+1

**Pull request merged**
