### PR TITLE
SPLICE-753 Removing Hadoop Tools

### PR DESCRIPTION
**Pull request by jleach4**
Removing hadoop-tools from build.  Jun will have a sister commit for backup and restore.

### CODE REVIEW

**Comment by jyuanca** [comment]
Need to pull in distcp 2.0, which depends on MR2

**Comment by scottfines** [comment]
+1. I assume that the distcp issue is related to backups/restore, which would be more appropriately treated in the ee repository

**Comment by jfilali** [comment]
+1

**Comment by jyuanca** [comment]
Merged a fix and close this one

**Pull request closed without merging**
