### PR TITLE
DB-9401 avoid costing control execution path in the presence of cross…

### PR DESCRIPTION
**Pull request by yxia92**
… join hint

### CODE REVIEW

**Comment by yxia92** [comment]
@arnaud-splice @dgomezferro Thanks for the review. I've fixed the spotbugs. Also I added a new commit to allow derived table to be the right table of a cross join when hinted. Please take a look, thanks!

**Comment by dgomezferro** [comment]
Looks good to me @yxia92 , one question though, why allowing only crossjoin when hinted for derived tables? Are we worried we don't support well all cases?

**Comment by yxia92** [comment]
@dgomezferro There are some costing issues related to cross join, and other join strategies, they are fixed in DB-9078 which is still under code review. I'm concerned that if I relax the cross join criteria without the fix of DB-9078, the chance of cross join being picked when it shouldn't will be increased.

**Comment by dgomezferro** [comment]
That makes sense @yxia92 , thanks!

**Pull request merged**
