### PR TITLE
SPLICE-950 Make activation classes eligible for GC

### PR DESCRIPTION
**Pull request by dgomezferro**
Invalidate statements when pushed out of the statement cache and store
only weak references on the DependencyManager

I've tested this running a script similar to what Gene uploaded concurrently with an IT run. A test for it will be added to the QA runs.

Tested it against JDK 7 & 8.

### CODE REVIEW

**Comment by jleach4** [comment]
+1

**Comment by jyuanca** [comment]
+1

**Comment by genedavis** [comment]
+1

**Comment by genedavis** [comment]
need version for branch-2.0 and make sure it works on Java 7

**Pull request merged**
