### PR TITLE
DB-10961 Get rid of the NodeFactory part 2

### PR DESCRIPTION
**Pull request by martinrupp**
iterative PR to get rid of NodeFactory / getNode

### CODE REVIEW

**Comment by martinrupp** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2920/

**Comment by martinrupp** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2922/

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request closed without merging**
