### PR TITLE
DB-10688 refactor sqlgrammar.jj (2.8)

### PR DESCRIPTION
**Pull request by martinrupp**

### CODE REVIEW

**Comment by martinrupp** [comment]
jenkins please test branch @cdh5.12.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1993/

**Review by carolp-503 — APPROVED** [review]
Approved for 2.8:
 - Trying to keep files in sync for any future merges
 - We've got another 2.8 change this week so will be building

**Comment by martinrupp** [comment]
jenkins please test branch @cdh5.12.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
