### PR TITLE
DB-9098 Raise SQLTimeoutException on query cancellation

### PR DESCRIPTION
**Pull request by dgomezferro**
Also report DB2 sqlcode

### CODE REVIEW

**Comment by dgomezferro** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST FAILED

**Comment by dgomezferro** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
