### PR TITLE
DB-8173 NSDSv1 Enabled primary key creation in createTable.

### PR DESCRIPTION
**Pull request by jpanko1**

### CODE REVIEW

**Comment by jpanko1** [comment]
jenkins please test branch @cdh6.3.0

**Comment by spliceci** [comment]
TEST FAILED

**Comment by jpanko1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED

**Comment by jpanko1** [comment]
Failure reason:
`Build timed out (after 360 minutes). Marking the build as failed.`

**Comment by jpanko1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
