### PR TITLE
DB-8200 fix NPE and wrong result for nested loop join with UNION oper…

### PR DESCRIPTION
**Pull request by yxia92**
…ation as right table

### CODE REVIEW

**Comment by yxia92** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by yxia92** [comment]
It seems that the fix is not complete, if the right side of nested loop join is a union with joins and subqueries, we still have issues, so temporarily close this PR.

**Comment by yxia92** [comment]
jenkins please retest branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
