### PR TITLE
Revert "Merge pull request #5291 from splicemachine/optimizer_staging"

### PR DESCRIPTION
**Pull request by arnaud-splice**
This reverts commit 8dfc5d5b0b131847072c0479775a3ff3e387a473, reversing
changes made to 9259ef097db805d8c02aecb8fe9384c07bdb31f5.

### CODE REVIEW

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2634/

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Review by msirek — APPROVED** [review]

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
