### PR TITLE
DB-11973 Fix bindTimezoneOperation's static call to SpliceDateFunctions

### PR DESCRIPTION
**Pull request by arnaud-splice**
## Short Description

Fix regression introduced by DB-11668

## Long Description

DB-11668 moved SpliceDateFunctions to another package without changing the reference in BinaryArithmeticOperatorNode. This PR fixes that.

## How to test
```
select timestamp(trim('2016-08-05-07.12.59.000000')) + current timezone from sysibm.sysdummy1;
```
does not fail anymore

### CODE REVIEW

**Review by dgomezferro — APPROVED** [review]

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by carolp-503 — APPROVED** [review]
+1

**Pull request merged**
