### PR TITLE
DB-8715 do not consider join predicate as scan start/stop key for Has…

### PR DESCRIPTION
**Pull request by yxia92**
…hableJoinStrategy, also fix an explain bug.
Please see [DB-8715](https://splicemachine.atlassian.net/browse/DB-8715) for details.

### CODE REVIEW

**Comment by yxia92** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST FAILED

**Comment by yxia92** [comment]
jenkins please retest branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
