### PR TITLE
DB-11335 improve start-splice-cluster (refactoring, -T threads for ma…

### PR DESCRIPTION
**Pull request by martinrupp**
# Description

bringing a bit more structure to start-splice-cluster by putting functionality in functions, add some comments

- adding option `-T <n>` for the number of threads used for building, e.g. `./start-splice-cluster -T 16` will use `mvn -T 16 -B …` , so building with 16 threads (faster)

- instead of using dots, using numbers to indicate progress (these numbers should be similar, so better way to guess how much time is left)

- added option -K : kill + reset database to clean state.

new output:

```
Starting Master and 1 Region Server. Log file is /Users/martinrupp/spliceengine/platform_it/splice.log
Starting Region Server /Users/martinrupp/spliceengine/platform_it/spliceRegionSvr2.log
Waiting for Master to be ready ... 0 - 1 - 2 - 3 - 4 - 5 - 6 - 7 - 8 - 9 - 10 - 11 - 12 - 13 - 14 - 15 - 16 - done!
Starting Region Server /Users/martinrupp/spliceengine4/platform_it/spliceRegionSvr2.log
Waiting for Region Server 2 to be ready ... 0 - 1 - 2 - 3 - 4 - done!
```

# How to test

`./start-splice-cluster` is an internal tool only used for development. If you want to test, run e.g. `./start-splice-cluster` .

### CODE REVIEW

**Review by msirek — COMMENTED** [review]
I like the display of numbers, to make it easy to compare startup times.  One possible improvement could be to display the actual startup time taken in minutes and seconds after splice comes up.

On my Ubuntu machine the first-time startup time decreased from 1:20 down to 1:13.
However, the warm restart time went from 42 seconds up to 46 seconds.  Maybe you could compare on your system and see if you see the same increase with this change.

I am measuring the wall clock time to do start-splice-cluster -k followed by start-splice-cluster -b

function bounce() {
    (cd /home/msirek/IdeaProjects/spliceengine
    ./start-splice-cluster -k
    ./start-splice-cluster -b -pcdh6.3.0 )
}

**Comment by martinrupp** [comment]
> I like the display of numbers, to make it easy to compare startup times. One possible improvement could be to display the actual startup time taken in minutes and seconds after splice comes up.
> 
> On my Ubuntu machine the first-time startup time decreased from 1:20 down to 1:13.
> However, the warm restart time went from 42 seconds up to 46 seconds. Maybe you could compare on your system and see if you see the same increase with this change.
> 
> I am measuring the wall clock time to do start-splice-cluster -k followed by start-splice-cluster -b
> 
> function bounce() {
> (cd /home/msirek/IdeaProjects/spliceengine
> ./start-splice-cluster -k
> ./start-splice-cluster -b -pcdh6.3.0 )
> }

you are right:
Ubuntu:
- new order (start start wait wait) 49/49/47
- old order (start wait start wait) 43/43/43

mac:
- new order (start start wait wait) 53/50/51
- old order (start wait start wait) 49/49/49

Not really sure why this is now 53/49 when it was 40/48 when i made my first tests. Maybe load on the system, heat, whatever. Ubuntu system was restarted and running on a well-cooled desktop machine, so these numbers should be good, and indicate what you said: It's slower. So i will change back to old startup order.

Thanks Marc!

**Comment by martinrupp** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by msirek — APPROVED** [review]

**Review by dgomezferro — APPROVED** [review]
Nice cleanup!

**Review by carolp-503 — APPROVED** [review]
+1

**Pull request merged**
