### PR TITLE
DB-10410: make data dictionary backward compatible(3.1)

### PR DESCRIPTION
**Pull request by jyuanca**
## Description
Make serialized objects in data dictionary backward compatible, so that we no longer break upgrade accidentally by changing writeExternal() method of an Externalizable, or public API of a Serializable class.  

## How to test
No functionality added or fixed, internally tested.

### CODE REVIEW

**Comment by jyuanca** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2565/

**Comment by jyuanca** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
