### PR TITLE
DB-9863 Fix check_table scans (2.8)

### PR DESCRIPTION
**Pull request by dgomezferro**

### CODE REVIEW

**Comment by dgomezferro** [comment]
jenkins please test branch @cdh5.12.2,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1077/

**Comment by martinrupp** [comment]
jenkins please test branch @cdh5.12.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1107/

**Comment by martinrupp** [comment]
+1

jenkins fails because of unrelated known issues in 2.8 branch
```
com.splicemachine.backup.BackupIT.testBackup
com.splicemachine.backup.BackupSchemaIT.testSchemaBackupRestore
com.splicemachine.backup.RestoreIT.testRestore
```
Jun is looking into it.

**Pull request merged**
