### PR TITLE
DB-11492 Enable automaticallyPurgeOldUpdates by default

### PR DESCRIPTION
**Pull request by arnaud-splice**

### CODE REVIEW

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Review by martinrupp — APPROVED** [review]

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2474/

**Review by dgomezferro — APPROVED** [review]

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by carolp-503 — APPROVED** [review]
+1

**Comment by hatyo** [comment]
Confirmed together with @arnaud-splice and @ascend1 that the failing test is not related to the PR, we'll open a JIRA for it, bringing this PR in.

**Pull request merged**
