### PR TITLE
DB-9058 (DB-9144 Subselect without alias + DB-9143 right of union derives name from left)

### PR DESCRIPTION
**Pull request by arnaud-splice**

### CODE REVIEW

**Comment by genedavis** [comment]
For completeness, can we have both UNION and UNION ALL IT test cases?

**Comment by dgomezferro** [comment]
Should this be extended to other set operations like EXCEPT and INTERSECT?

**Comment by arnaud-splice** [comment]
> For completeness, can we have both UNION and UNION ALL IT test cases?

Done

**Comment by arnaud-splice** [comment]
> Should this be extended to other set operations like EXCEPT and INTERSECT?

Good point. I would do it in a separate change once build servers are back online though. Unless we think it's blocking.

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST FAILED

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
