### PR TITLE
DB-11220 Re-do DB-11186.

### PR DESCRIPTION
**Pull request by msirek**
This reimplements DB-11186 by ignoring the null cell entries instead of not adding them to the list of found entries.  Some interfaces rely on checking whether a base row exists by checking the ordinal position of the results list for a null or empty cell.

### CODE REVIEW

**Comment by msirek** [comment]
jenkins please test branch @mem

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by msirek** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Review by jyuanca — APPROVED** [review]

**Review by jpanko1 — APPROVED** [review]

**Comment by cloudspliceci** [comment]
TEST FAILED
https://jenkins.build.splicemachine-dev.io/job/AutomatedTesting/job/spliceengine-PR/121/

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by martinrupp — APPROVED** [review]

**Review by carolp-503 — APPROVED** [review]
+1

**Pull request merged**
