### PR TITLE
DB-8577 Isolate compaction to its own spark queue

### PR DESCRIPTION
**Pull request by arnaud-splice**

### CODE REVIEW

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST FAILED

**Comment by arnaud-splice** [comment]
jenkins please retest branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by changli6** [comment]
Looks good @arnaud-splice .
Questions:
1. If we set splice.olap_server.isolated.compaction = true, but the "compaction" queue doesn't exist in YARN, what is the error?
2. Could user set the compaction queue name instead of "compaction" ?

**Comment by jyuanca** [comment]
It would be more flexible if compaction queue name is configurable

**Comment by arnaud-splice** [comment]
> Looks good @arnaud-splice .
> Questions:
> 
> 1. If we set splice.olap_server.isolated.compaction = true, but the "compaction" queue doesn't exist in YARN, what is the error?
> 2. Could user set the compaction queue name instead of "compaction" ?

1. If we set splice.olap_server.isolated.compaction = true, a compaction queue should exist in YARN. If that is not the case for some reason, the error message will be the same as the one which would be issued if no OlapServer exists.

2. Done

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
