### PR TITLE
DB-12304 Fix call sites of getKeyColumnPosition (3.1)

### PR DESCRIPTION
**Pull request by ascend1**
See https://github.com/splicemachine/spliceengine/pull/5652.

### CODE REVIEW

**Comment by ascend1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by cloudspliceci** [comment]
TEST SUCCEEDED +1

**Review by carolp-503 — APPROVED** [review]
Approved for 3.1

**Comment by carolp-503** [comment]
For posterity - this addresses an issue related to DB-9898

**Pull request merged**
