### PR TITLE
DB-12224 Permutate system index columns to prioritize schemaId column (3.1)

### PR DESCRIPTION
**Pull request by arnaud-splice**
## All DB-12224 PRs

[spliceengine master](https://github.com/splicemachine/spliceengine/pull/5646)
[spliceengine-ee master](https://github.com/splicemachine/spliceengine-ee/pull/653)
[spliceengine branch-3.1](https://github.com/splicemachine/spliceengine/pull/5647)
[spliceengine-ee branch-3.1](https://github.com/splicemachine/spliceengine-ee/pull/654)

### CODE REVIEW

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by cloudspliceci** [comment]
TEST SUCCEEDED +1

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by cloudspliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/3311/

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by cloudspliceci** [comment]
TEST SUCCEEDED +1

**Review by carolp-503 — APPROVED** [review]
Approved for 3.1

**Pull request merged**
