### PR TITLE
DB-11764 TOSCA rich client test - query complexity

### PR DESCRIPTION
**Pull request by ipraznik-splice**
## Short Description
The too complex query can cause a java.io.UTFDataFormatException.

## Long Description
if DataOutputStream.writeUTF is used, the length of the parameter cannot exceed 65535. This is due to the fact, that writeUTF uses the first two bytes to code the length of the byte array and has a check for this:
```
if (utflen > 65535)
            throw new UTFDataFormatException(
                "encoded string too long: " + utflen + " bytes");
```
In particular, in this case, the problem is with ProjectRestrictOperation.filterPred, when the query has too many values in 'in' clause, for example. CONSTANT_Utf8_info.put cannot serialize a value to ClassFormatOutput.

## How to test
Use many values for in clause in the query, like select * from [TABLE] where id in('id1','id2', .... 'idn'), that the length of the string 
```
in('id1','id2', .... 'idn')
```
is greater than 65535. It's not necessary, that all ids are presented in the database. Important only the length.

### CODE REVIEW

**Comment by ipraznik-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Review by msirek — APPROVED** [review]
Great fix!

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2731/

**Comment by ipraznik-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2732/

**Comment by ipraznik-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by jyuanca — APPROVED** [review]

**Review by carolp-503 — APPROVED** [review]
+1

**Pull request merged**
