### PR TITLE
DB-11475 Respect the requested SQLDecimal precision

### PR DESCRIPTION
**Pull request by jyuanca**

### CODE REVIEW

**Comment by jyuanca** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2492/

**Comment by jyuanca** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2493/

**Review by arnaud-splice — APPROVED** [review]

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2495/

**Comment by arnaud-splice** [comment]
I cancelled the last Jenkins test I requested because the error is fixed by DB-11507 (not yet merged)

**Review by jpanko1 — APPROVED** [review]

**Review by carolp-503 — APPROVED** [review]
+1

Pair programmed by jyuanca and msirek, plus review by arnaud-splice

And thanks, jpanko!  Added your review too while I wasn't looking!

**Pull request merged**
