### PR TITLE
DB-11126 support CURRENT TIMEZONE.

### PR DESCRIPTION
**Pull request by hatyo**
In this PR we provide support to [DB2's CURRENT TIMEZONE](https://www.ibm.com/support/producthub/db2/docs/content/SSEPGG_11.5.0/com.ibm.db2.luw.sql.ref.doc/doc/r0005887.html?pos=2).

According to the documentation, `CURRENT TIMEZONE` (or `CURRENT_TIMEZONE`) returns the server's timezone offset as `DEC(6,0)`. We can also use with a timestamp expression to return it in UTC (GMT).

Some example how this works (all examples assume that the server is running in IST (05:30+GMT)

```
splice> select current_timezone from t1;
1
-------
53000 -- decimal(6,0)

splice> select current_timestamp from  t1;
1
-----------------------------
2021-01-20 20:23:10.516897

splice> select current_timestamp - current_timezone from t1;
1
-----------------------------
2021-01-20 14:53:02.12 -- we shift 5:30 hours earlier

splice> select current_timestamp + current_timezone from t1;
1
-----------------------------
2021-01-21 01:53:24.504 -- we shift 5:30 hours later

-- it can also work with expressions
splice> select timestampadd(sql_tsi_year, 3, timestamp('2020-11-11 13:10:11.12345')) - current_timezone from   t1;
1
-----------------------------
2023-11-11 07:40:11.123
```

Adding integration tests to this feature is somehow difficult since it requires starting the cluster with different timezones e.g. [as explained here](https://docs.oracle.com/javase/9/troubleshoot/time-zone-settings-jre.htm#JSTGD377). Therefore, I think we would cooperate with the QA team to test this feature end to end.

### CODE REVIEW

**Comment by hatyo** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Review by msirek — APPROVED** [review]

**Comment by cloudspliceci** [comment]
TEST FAILED
https://jenkins.build.splicemachine-dev.io/job/AutomatedTesting/job/spliceengine-PR/141/

**Review by dgomezferro — APPROVED** [review]

**Review by carolp-503 — APPROVED** [review]
+1

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by arnaud-splice — COMMENTED** [review]
+1

**Pull request merged**
