### PR TITLE
DB-9506 fix zlib compression for Parquet and AVRO

### PR DESCRIPTION
**Pull request by martinrupp**

### CODE REVIEW

**Comment by jpanko1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED

**Comment by martinrupp** [comment]
rebased

**Comment by martinrupp** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by martinrupp** [comment]
possible sporadic
```
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/886/console
sporadic on master? (2nd time succeed)
2020-06-15|22:02:31,528 [ERROR] Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 6.44 s <<< FAILURE! - in com.splicemachine.foreignkeys.ForeignKey_Action_IT
2020-06-15|22:02:31,529 [ERROR] onDeleteNoAction_primaryKey_initializeWriteContextOfParentFirst(com.splicemachine.foreignkeys.ForeignKey_Action_IT)  Time elapsed: 1.592 s  <<< FAILURE!
java.lang.AssertionError: expected query to fail: delete from P where a = 4
	at com.splicemachine.foreignkeys.ForeignKey_Action_IT.assertQueryFail(ForeignKey_Action_IT.java:171)
	at com.splicemachine.foreignkeys.ForeignKey_Action_IT.onDeleteNoAction_primaryKey_initializeWriteContextOfParentFirst(ForeignKey_Action_IT.java:133)
```

**Pull request merged**
