### PR TITLE
DB-10421 Fix multi-column in-list on index expressions

### PR DESCRIPTION
**Pull request by ascend1**

### CODE REVIEW

**Review by msirek — APPROVED** [review]

**Review by martinrupp — APPROVED** [review]

**Review by yxia92 — APPROVED** [review]

**Comment by ascend1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by ascend1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by carolp-503 — APPROVED** [review]
+1

**Pull request merged**
