### PR TITLE
DB-8138: extract columns correctly for update trigger(2.7)

### PR DESCRIPTION
**Pull request by jyuanca**

### CODE REVIEW

**Comment by jyuanca** [comment]
jenkins please test branch @cdh5.13.3

**Comment by jyuanca** [comment]
jenkins please test branch @cdh5.12.0

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by carolp-503** [comment]
Approved for R2.7

**Pull request merged**
