### PR TITLE
DB-11580 Use Spark Dataset for trigger rows (3.1)

### PR DESCRIPTION
**Pull request by msirek**
## https://github.com/splicemachine/spliceengine/pull/5470 must merge before this PR.

### CODE REVIEW

**Comment by msirek** [comment]
IT run:
http://nexus.splicemachine.com:8080/job/spliceengine-branch/job/spliceengine-branch/2102/default/

**Comment by msirek** [comment]
IT run:
http://nexus.splicemachine.com:8080/job/spliceengine-branch/job/spliceengine-branch/2104/default/

**Comment by msirek** [comment]
jenkins please test branch @dbaas3.0

**Comment by msirek** [comment]
Latest IT run:
http://nexus.splicemachine.com:8080/job/spliceengine-branch/job/spliceengine-branch/2107/default/

**Review by carolp-503 — APPROVED** [review]
Approved for 3.1

**Comment by msirek** [comment]
Latest IT run:
http://nexus.splicemachine.com:8080/job/spliceengine-branch/job/spliceengine-branch/2108/default/

**Pull request merged**
