### PR TITLE
DB-8846 changes in CDH-installation.md: Java Configuration Options for HBase Master (2.8)

### PR DESCRIPTION
**Pull request by martinrupp**
aligning some of the 3.0/master changes (note ORC was only a problem on CDH6.3.0, so not on branch-2.8)
- removed -Dspark.compaction.reserved.slots=4
- removed  -Dsplice.spark.shuffle.compress=false
- removed -XX:MaxPermSize=512M
- -Dsplice.spark.master=yarn-client -> -Dsplice.spark.master=yarn

### CODE REVIEW

**Comment by martinrupp** [comment]
note to myself:
👎  missing config in other files

**Comment by martinrupp** [comment]
ready for review

**Comment by martinrupp** [comment]
jenkins please test branch @cdh5.12.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
