### PR TITLE
DB-10506 fix SET_PURGE_DELETED_ROWS using unset minRetentionPeriod

### PR DESCRIPTION
**Pull request by martinrupp**
fixes failed test com.splicemachine.derby.impl.sql.execute.actions.TempTableIT#testSystemProceduresOnTempTable

### CODE REVIEW

**Comment by martinrupp** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1717/

**Review by msirek — APPROVED** [review]

**Review by carolp-503 — APPROVED** [review]
+1

**Review by arnaud-splice — APPROVED** [review]

**Comment by martinrupp** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
