### PR TITLE
DB-10619 Support manipulation on timestamp column 

### PR DESCRIPTION
**Pull request by arnaud-splice**

### CODE REVIEW

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by martinrupp — APPROVED** [review]
nice! i especially like moving code out of sqlgrammar.jj (Note to myself: will conflict with https://github.com/splicemachine/spliceengine/pull/4517/ ).

**Review by dgomezferro — APPROVED** [review]

**Review by ipraznik-splice — APPROVED** [review]

**Review by carolp-503 — APPROVED** [review]
+1

**Pull request merged**
