### PR TITLE
DB-8931 Support ^= for Not Equals syntax

### PR DESCRIPTION
**Pull request by changli6**

### CODE REVIEW

**Comment by changli6** [comment]
jenkins please test @cdh5.12.2

**Comment by changli6** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by changli6** [comment]
jenkins please test branch @mem

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
