### PR TITLE
DB-10707 NSDS Insert with Trigger

### PR DESCRIPTION
**Pull request by jpanko1**

### CODE REVIEW

**Review by bklo94 — APPROVED** [review]

**Comment by jpanko1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Review by dgomezferro — APPROVED** [review]

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1922/

**Review by msirek — CHANGES_REQUESTED** [review]
This is a great fix.  Please make the same change in UpdateOperation.java and DeleteOperation.java to handle UPDATE and DELETE triggers as well.

**Comment by jpanko1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by jpanko1** [comment]
> This is a great fix. Please make the same change in UpdateOperation.java and DeleteOperation.java to handle UPDATE and DELETE triggers as well.

Made the change for the update and delete operations in commit https://github.com/splicemachine/spliceengine/pull/4560/commits/c861f5acdbe955a91522639af95d5312276b3232

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
