### PR TITLE
DB-11435 Revert DB-11258

### PR DESCRIPTION
**Pull request by jpanko1**
Automatic revert from the [PR](https://github.com/splicemachine/spliceengine/pull/5116) didn't work: "Sorry, this pull request couldn’t be reverted automatically. It may have already been reverted, or the content may have changed since it was merged."

Did a rebase to remove [DB-11258](https://splicemachine.atlassian.net/browse/DB-11258)

### CODE REVIEW

**Comment by jpanko1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2443/

**Review by msirek — APPROVED** [review]

**Comment by jpanko1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2445/

**Comment by jpanko1** [comment]
Replaced by https://github.com/splicemachine/spliceengine/pull/5165

**Pull request closed without merging**
