### PR TITLE
DB-10232-2 external CSV tables write correctly PARTITIONED BY

### PR DESCRIPTION
**Pull request by martinrupp**
2nd try fixing the previous errors on jenkins

### CODE REVIEW

**Comment by martinrupp** [comment]
jenkins please test branch @cdh6.3.0

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by martinrupp** [comment]
jenkins please test branch @cdh6.3.0

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by arnaud-splice — APPROVED** [review]

**Review by dgomezferro — APPROVED** [review]

**Review by ascend1 — APPROVED** [review]

**Pull request merged**
