### PR TITLE
DB-10461 Add format parameter to char() and varchar() functions

### PR DESCRIPTION
**Pull request by ascend1**

### CODE REVIEW

**Comment by ascend1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Review by dgomezferro — APPROVED** [review]

**Comment by dgomezferro** [comment]
@ascend1 have you tested these functions in Native Spark execution? See ProjectRestrictSparkExpressionIT for instance

**Review by martinrupp — APPROVED** [review]

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1849/

**Comment by ascend1** [comment]
> @ascend1 have you tested these functions in Native Spark execution? See ProjectRestrictSparkExpressionIT for instance

Hmm, I didn't. I'll take a look.

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by ascend1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by ascend1** [comment]
> @ascend1 have you tested these functions in Native Spark execution? See ProjectRestrictSparkExpressionIT for instance

I tested the queries in Spark and they work. I added a few tests cases in `ProjectRestrictSparkExpressionIT`. Since functionality is tested thoroughly in `FunctionIT`, tests newly added mainly ensures the queries run in Spark and return the same result as in OLTP.

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
