### PR TITLE
DB-11055 NSDS Merge Into

### PR DESCRIPTION
**Pull request by jpanko1**

### CODE REVIEW

**Comment by jpanko1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by Ben-Epstein — APPROVED** [review]

**Comment by jpanko1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Review by msirek — APPROVED** [review]

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by dgomezferro — CHANGES_REQUESTED** [review]
Change looks good, thanks for the quick turnaround @jpanko1 ! 
I'd like to have some tests for update & insert triggers, since that's the main driver behind this feature, could you add them?

**Comment by jpanko1** [comment]
> Change looks good, thanks for the quick turnaround @jpanko1 !
> I'd like to have some tests for update & insert triggers, since that's the main driver behind this feature, could you add them?

Thanks @dgomezferro, the mergeInto trigger tests are added in commits https://github.com/splicemachine/spliceengine/pull/4884/commits/1b01be573a8e85d2c3fbad070f26f2ad10fe9b36 and https://github.com/splicemachine/spliceengine/pull/4884/commits/dd9aec03bebb228387c8aabd0bff24e188348e63

**Comment by jpanko1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2175/

**Comment by jpanko1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by dgomezferro — APPROVED** [review]
Awesome, thanks @jpanko1 !

**Review by carolp-503 — APPROVED** [review]
+1

**Pull request merged**
