### PR TITLE
DB-10908 Support Spark 3.0.1

### PR DESCRIPTION
**Pull request by ipraznik-splice**

### CODE REVIEW

**Comment by ipraznik-splice** [comment]
jenkins please test branch @dbaas3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2088/

**Comment by ipraznik-splice** [comment]
jenkins please test branch @dbaas3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2096/

**Review by jyuanca — APPROVED** [review]

**Review by arnaud-splice — APPROVED** [review]

**Review by carolp-503 — APPROVED** [review]
+1

**Pull request merged**
