### PR TITLE
DB-9786 fix merge region retry logic.

### PR DESCRIPTION
**Pull request by hatyo**

### CODE REVIEW

**Review by carolp-503 — APPROVED** [review]
+1

**Review by jyuanca — APPROVED** [review]

**Comment by ipraznik-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2185/

**Review by dgomezferro — APPROVED** [review]

**Comment by ipraznik-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2187/

**Pull request merged**
