### PR TITLE
DB-10780 Relax the requirements of constructing a multi-probe scan

### PR DESCRIPTION
**Pull request by ascend1**

### CODE REVIEW

**Comment by ascend1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Review by msirek — APPROVED** [review]
The fix looks good to me.

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by OlegMazurov — APPROVED** [review]

**Review by dgomezferro — APPROVED** [review]

**Review by carolp-503 — APPROVED** [review]
+1

We need to thoroughly test this one for both performance and correctness.

**Pull request merged**
