### PR TITLE
SPLICE-2362 Native Spark join with inequality conditions.

### PR DESCRIPTION
**Pull request by msirek**
Opening a new PR to re-merge the following, which was backed out:
https://github.com/splicemachine/spliceengine/pull/2893

The issue was the default spark version when no platform is specified was 2.1.0, but Spark 2.2 jars are required for compilation to succeed.  
The previous PR was approved, so only the most recent commit on this branch needs to be reviewed.

### CODE REVIEW

**Comment by msirek** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST FAILED

**Comment by msirek** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
