### PR TITLE
SPLICE-1900: Incorrect error message while reading data from Empty external table of AVRO file format.

### PR DESCRIPTION
**Pull request by stpabhi**

### CODE REVIEW

**Comment by stpabhi** [comment]
@jleach4 @dgomezferro @jyuanca please review

**Comment by snowspeeder** [comment]
can you please also do branch-2.6 PR?

**Comment by stpabhi** [comment]
@snowspeeder PR for 2.6 https://github.com/splicemachine/spliceengine/pull/1361

**Comment by wtang16** [comment]
The same code is applicable in 2.5. Please have a PR for branch-2.5 as well. Thanks.

**Comment by stpabhi** [comment]
@wtang16 PR for 2.5 https://github.com/splicemachine/spliceengine/pull/1364

**Comment by wtang16** [comment]
AVRO format is probably not supported on 2.5. We can remove that shipment.

**Pull request merged**
