### PR TITLE
DB-8195 Calculate average split size for the splits=n hint. (2.7)

### PR DESCRIPTION
**Pull request by msirek**
* DB-8195 Calculate average split size for the splits=n hint.

* DB-8195 Get region sizes in parallel instead of using a serial record reader.

### CODE REVIEW

**Comment by msirek** [comment]
jenkins please test branch @cdh5.12.0

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by msirek** [comment]
jenkins please test branch @cdh5.16.1

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
