### PR TITLE
DB-5007: Adding correct error message and test

### PR DESCRIPTION
**Pull request by scottfines**
It turns out that there was a test, it just wasn't a very clean one; it didn't check for precise error messages, so you didn't see what was actually happening.

### CODE REVIEW

**Comment by jyuanca** [comment]
+1

**Comment by jeffcunningham** [comment]
+1, but there are other tests in that class that use the same (imprecise) mechanism to test for exception msgs. If you're not going to bite off improving those too, you should crate a Jira.

**Comment by scottfines** [comment]
+Jeff: Agreed. I'd like to keep this particular PR clean and focused, so I'll create a JIRA.

**Comment by jleach4** [comment]
+1 Thanks.

**Comment by scottfines** [comment]
Turns out this causes a breakage in error handling elsewhere. Closing this PR, will open a new one once I resolve the other problems.

**Pull request closed without merging**
