### PR TITLE
DB-11127 Unify code path for concatenation operator and function

### PR DESCRIPTION
**Pull request by ascend1**

### CODE REVIEW

**Review by ipraznik-splice — APPROVED** [review]

**Comment by ascend1** [comment]
jenkins please test branch @cdh6.3.0

**Review by dgomezferro — APPROVED** [review]

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2408/

**Comment by ascend1** [comment]
jenkins please test branch @cdh6.3.0

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2416/

**Comment by ascend1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by carolp-503 — APPROVED** [review]
+1

**Pull request merged**
