### PR TITLE
DB-12097 better SQL errors

### PR DESCRIPTION
**Pull request by martinrupp**
## Short Description
improve error messages with more detailed description what's wrong with the SQL

## Example
SQL with errors:
```
CREATE TABLE MY_TABLE (
L_ORDERKEY BIGINT NOT NULL,
L_PARTKEY INTEGER NOT DECIMAL,
L_SUPPKEY INTEGER NOT NULL,
L_LINENUMBER INTEGER NOT NULL,
L_QUANTITY DECIMAL(15,2),
L_EXTENDEDPRICE DECIMAL(15,2),
L_DISCOUNT DECIMAL(15,2)
);
```

Error Message before

```
ERROR 42X01: Syntax error: Encountered "DECIMAL" at line 3, column 23.
```

New Error Message

```
ERROR 42X01: Syntax error: Encountered "DECIMAL" at line 3, column 23.
Was expecting:
    "null" ...
    
1: CREATE TABLE MY_TABLE (
2: L_ORDERKEY BIGINT NOT NULL,
3: L_PARTKEY INTEGER NOT DECIMAL,
                         ^^^^^^^---------
4: L_SUPPKEY INTEGER NOT NULL,
5: L_LINENUMBER INTEGER NOT NULL,
6:L_QUANTITY DECIMAL(15,2),
```

### CODE REVIEW

**Comment by martinrupp** [comment]
please check first commit for code changes, second one is only indentation/tab->space change

**Comment by martinrupp** [comment]
SpotBugs is weird for this one, it is complaining about this:
```
1 specific errors to fix before this PR can be merged:
[ERROR] Unwritten public or protected field: com.splicemachine.db.impl.sql.compile.Token.next [com.splicemachine.db.impl.sql.compile.ParseException] At ParseException.java:[line 176] UWF_UNWRITTEN_PUBLIC_OR_PROTECTED_FIELD
```
however i have SuppressFBWarnings both for class and function in this file. I even tried (locally) to put com.splicemachine.db.impl.sql.compile.ParseException in findbugs-exclude-filter.xml, but also doesn't help.
So i would suggest to ignore the SpotBugs issue for this one.

**Comment by martinrupp** [comment]
tried adding
```
<Match>
    <!-- Spotbugs somehow doesn't accept the SuppressFBWarnings in here -->
    <Class name="~.*ParseException.*"/>
</Match>
```
to `findbugs-exclude-filter.xml`, but doesn't help

**Comment by martinrupp** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Review by arnaud-splice — APPROVED** [review]
Awesome change!

**Review by jyuanca — APPROVED** [review]

**Review by carolp-503 — APPROVED** [review]
+1

**Comment by martinrupp** [comment]
**to the sprint moderator:**
There's some weird thing going on with SpotBugs and the generated code from the parser. I tried multiple things (SuppressFBWarnings for function, SuppressFBWarnings for class, findbugs-exclude-filter.xml for whole file), nothing worked, and i couldn't fix this. I would suggest to merge this despite SpotBugs complaining.

**Review by dgomezferro — APPROVED** [review]

**Comment by hatyo** [comment]
@martinrupp I managed to suppress SpotBugs issues by directly suppressing the (falsely identified) error `UWF_UNWRITTEN_PUBLIC_OR_PROTECTED_FIELD` on `Token.next`.

**Comment by martinrupp** [comment]
jenkins please test branch @cdh6.3.0

**Comment by cloudspliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
