### PR TITLE
SPLICE-2134 Fixing Column Sequencing for views, issue shows up with c…

### PR DESCRIPTION
**Pull request by jleach4**
…olumn level permissions on views

Customers should recreate views to incorporate these changes for permissions on views.

### CODE REVIEW

**Comment by jleach4** [comment]
I think we punt on it and ask people to recreate views.  We are swamped.

**Comment by wtang16** [comment]
We'll need to see if we can recreate system views automatically. We don't have to provide an update script for user views though. 

Also, we'll need to ship this to 2.7/master branches.

**Comment by yxia92** [comment]
If I understand correctly, this bug only affects user views, the column description for system views (sys.systablestatistics, sys.syscolumnstatistics) are created correctly. So we just need to drop and rereate user views.

**Comment by jleach4** [comment]
That is correct…

John

**Pull request merged**
