### PR TITLE
DB-10944 DB2 compatible casting format from floating point to string

### PR DESCRIPTION
**Pull request by ascend1**

### CODE REVIEW

**Comment by ascend1** [comment]
jenkins please test branch @cdh6.3.0

**Comment by ascend1** [comment]
jenkins please test branch @cdh6.3.0

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by jyuanca — APPROVED** [review]

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2114/

**Comment by ascend1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2116/

**Review by msirek — APPROVED** [review]
The change looks good.  I'm just wondering if we want to control the behavior with a database property, or do we actually want to change our casting behavior for Splice to always match DB2 for floating point to string.  It is possible there's a customer with an application that depends on how Splice currently does this cast.

**Comment by jpanko1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by ascend1** [comment]
> The change looks good. I'm just wondering if we want to control the behavior with a database property, or do we actually want to change our casting behavior for Splice to always match DB2 for floating point to string. It is possible there's a customer with an application that depends on how Splice currently does this cast.

Yes, Carol, Arnaud, and I had a discussion about this. There is some effort on implementing a DB2mode and it's supposed to be applied in these places. The change should be easy to adapt once it's there.

**Comment by ascend1** [comment]
> The change looks good. I'm just wondering if we want to control the behavior with a database property, or do we actually want to change our casting behavior for Splice to always match DB2 for floating point to string. It is possible there's a customer with an application that depends on how Splice currently does this cast.

That's a good point. Arnaud, Carol, and I had a discussion on this and I remember that we don't think any existing customer currently rely on this in their applications. So should be OK for now. Further, there is no consensus on what kind of flags we need for each of these cases yet. IMHO it's good to have mode flag(s), but more discussion needed on this topic. To not block the build, I'll open a Jira and keep working on it.

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2120/

**Comment by jpanko1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Review by carolp-503 — APPROVED** [review]
+1

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
