### PR TITLE
DB-10665 fix TypeDescriptorImpl serialization problem

### PR DESCRIPTION
**Pull request by martinrupp**

### CODE REVIEW

**Comment by dgomezferro** [comment]
@martinrupp are you generating new serialVersionUIDs or are you making explicit the existing ones? Would this break upgrades?

**Comment by martinrupp** [comment]
> @martinrupp are you generating new serialVersionUIDs or are you making explicit the existing ones? Would this break upgrades?

i'm making the existing ones explicit, e.g. the hashcodes of the written objects don't change, so there's no change, see
https://github.com/splicemachine/spliceengine/pull/4501/files#diff-49a937db96d8f912ec4f68ac19692ef4e661ac617d2d6d71628bd756db688ae4R254

**Comment by martinrupp** [comment]
> Would this break upgrades?

No, it was the intention to NOT break updates. Without having these checks, @arnaud-splice changes that added the hash function would have broken upgrades (!).

**Review by dgomezferro — APPROVED** [review]
@martinrupp I see, thanks! Looks good!

**Comment by martinrupp** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Review by arnaud-splice — CHANGES_REQUESTED** [review]

**Comment by arnaud-splice** [comment]
Excellent PR!

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1880/

**Review by arnaud-splice — APPROVED** [review]

**Comment by martinrupp** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Review by jyuanca — APPROVED** [review]

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1899/

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1900/

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1907/

**Comment by msirek** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1919/

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1925/

**Pull request merged**
