### PR TITLE
DB-11118 Add DB2-like RTRIM functionality

### PR DESCRIPTION
**Pull request by msirek**
Adds support for:
1. System function SYSFUN.RTRIM, which trims all trailing whitespaces off a string expression, e.g.

> values(sysfun.rtrim('abc   ') || sysfun.rtrim('abc   '));
> 1                                                                                                                                                                                                                                                               
> //----------------------------------------------------------------
> abcabc     
                                
2. An extra parameter to the RTRIM operator/function which supports stripping multiple occurrences of a trim string from the end of an expression, e.g.

> values (rtrim('abcdefdef','def'));
> 1        
> //---------
> abc

### CODE REVIEW

**Comment by msirek** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2354/

**Comment by msirek** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2356/

**Comment by msirek** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by arnaud-splice — APPROVED** [review]

**Review by ipraznik-splice — APPROVED** [review]

**Review by carolp-503 — APPROVED** [review]
+1

**Pull request merged**
