### PR TITLE
DB-10527 support for the comparison between bit data type and regular…

### PR DESCRIPTION
**Pull request by yxia92**
… string type

### CODE REVIEW

**Comment by yxia92** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by jyuanca — APPROVED** [review]

**Review by hatyo — APPROVED** [review]
Great!

**Review by carolp-503 — APPROVED** [review]
+1

**Pull request merged**
