### PR TITLE
Splice 1325

### PR DESCRIPTION
**Pull request by OlegMazurov**
A global thread pool is created. The default maximum number of threads in the pool is 256.
The pool is used in NLJoinFunction to avoid new thread pool creation on every invocation.

### CODE REVIEW

**Comment by jleach4** [comment]
Make sure your thread pool is in a state engine.  You create it but I did not see you shut it down.  If you have thread pools open, I believe HBase will not shutdown gracefully (I believe we had that problem before).

**Comment by OlegMazurov** [comment]
I'd introduce a shutdown() or unloadDriver() method to EngineDriver then.
The thread pool could be shutdown there.

**Comment by OlegMazurov** [comment]
Pool threads stuck in I/O (waiting for server response) will prevent the
JVM from exiting. Creating all pool threads as daemon.
Assuming the service is stopped asynchronously, I believe we can shutdown
the pool more aggressively.

**Comment by jleach4** [comment]
+1

**Pull request merged**
