### PR TITLE
DB-7847: flush should not block backup

### PR DESCRIPTION
**Pull request by jyuanca**

### CODE REVIEW

**Comment by jyuanca** [comment]
jenkins please test branch @cdh5.13.0

**Comment by spliceci** [comment]
TEST FAILED

**Comment by spliceci** [comment]
TEST FAILED

**Comment by jyuanca** [comment]
jenkins please test branch @cdh5.14.0

**Comment by spliceci** [comment]
TEST FAILED

**Comment by jyuanca** [comment]
jenkins please retest branch @cdh5.14.0

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by MurrayBrown** [comment]
What IT tests do we have that cover hbase flushing? (I realize that is an asynchronous process and probably very difficult to test....)

**Comment by jyuanca** [comment]
Yes, hard to write an IT. I manually tested.

**Comment by yxia92** [comment]
@jyuanca I see that this is one of the two enhancements in DB-6871 ( #2530 ) which was reverted. I want to confirm that [the failure case](
https://splicemachine.atlassian.net/browse/DB-6871?focusedCommentId=58655&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-58655) which caused DB-6871 to be reverted is from the other enhancement about keeping track of compaction and split. Am I right?

**Comment by jyuanca** [comment]
@yxia92 Yes, you are right.

**Pull request merged**
