### PR TITLE
DB-6106 Fix limit on multiple partitions on Spark (2.5)

### PR DESCRIPTION
**Pull request by dgomezferro**

### CODE REVIEW

**Comment by yxia92** [comment]
need to port to branch-2.6 also?

**Comment by OlegMazurov** [comment]
Daniel, to avoid a gap in 2.6 you need to create another PR for that branch.

**Comment by dgomezferro** [comment]
@wtang16  has to approve backports to 2.6, I've asked him in the ticket

**Comment by wtang16** [comment]
Approved.

**Pull request merged**
