### PR TITLE
DB-7980 Order constraints in show create table result

### PR DESCRIPTION
**Pull request by changli6**
jenkins please test branch @cdh5.12.2

### CODE REVIEW

**Comment by changli6** [comment]
jenkins please test branch @cdh5.12.2

**Comment by changli6** [comment]
jenkins please test branch @cdh5.13.3

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by changli6** [comment]
jenkins please test branch @cdh5.14.0

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
