### PR TITLE
DB-10605 Replace guava packages by splice shaded guava

### PR DESCRIPTION
**Pull request by ipraznik-splice**

### CODE REVIEW

**Comment by ipraznik-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by ipraznik-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Review by jyuanca — APPROVED** [review]

**Review by bklo94 — APPROVED** [review]

**Review by OlegMazurov — APPROVED** [review]

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1792/

**Comment by ipraznik-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by ipraznik-splice** [comment]
jenkins please test branch @hdp3.1.5,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1793/

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1798/

**Review by carolp-503 — APPROVED** [review]
+1

**Comment by ipraznik-splice** [comment]
jenkins please test branch @hdp3.1.5,skipTestsLongerThan2Minutes

**Review by martinrupp — APPROVED** [review]

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1799/

**Pull request merged**
