### PR TITLE
DB-10656: detect missing splits correctly

### PR DESCRIPTION
**Pull request by jyuanca**

### CODE REVIEW

**Comment by jyuanca** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Review by dgomezferro — APPROVED** [review]

**Review by yxia92 — APPROVED** [review]
+1

**Review by carolp-503 — APPROVED** [review]
+1

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
