### PR TITLE
DB-10871 more efficient API for getting active Txns

### PR DESCRIPTION
**Pull request by hatyo**

### CODE REVIEW

**Comment by hatyo** [comment]
jenkins please test branch @cdh6.3.0

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2028/

**Review by dgomezferro — COMMENTED** [review]
Change looks good @hatyo ! I'm not sure if we are always registering the 'destination' tables though, because it looks like we are only registering them when we create the transaction but a transaction could start writing to a different table later.
Btw, I'm not sure we are correctly registering written to tables for transactions that write through triggers, for instance. Could you double check that?

**Comment by hatyo** [comment]
> Change looks good @hatyo ! I'm not sure if we are always registering the 'destination' tables though, because it looks like we are only registering them when we create the transaction but a transaction could start writing to a different table later.
> Btw, I'm not sure we are correctly registering written to tables for transactions that write through triggers, for instance. Could you double check that?

Thanks @dgomezferro, I will check that.

**Pull request closed without merging**
