### PR TITLE
DB-8794 WIP Reduce complexity of compaction from quasilinear to linear

### PR DESCRIPTION
**Pull request by arnaud-splice**

### CODE REVIEW

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh5.14.0

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh5.14.0

**Comment by spliceci** [comment]
TEST FAILED

**Comment by arnaud-splice** [comment]
jenkins please retest branch @cdh5.14.0

**Comment by spliceci** [comment]
TEST FAILED

**Comment by arnaud-splice** [comment]
jenkins please retest branch @cdh5.14.0

**Comment by spliceci** [comment]
TEST FAILED

**Comment by arnaud-splice** [comment]
jenkins please retest branch @cdh5.14.0

**Comment by spliceci** [comment]
TEST FAILED

**Comment by msirek** [comment]
@arnaud-splice Could you please add a short description of the complexity issue you're fixing?  It would help with the code review.

**Comment by arnaud-splice** [comment]
> @arnaud-splice Could you please add a short description of the complexity issue you're fixing? It would help with the code review.

Will do. But this is still very much work in progress, so I haven't formalised it yet, nor have I added reviewers.

In the meantime, what I am trying to achieve is the following:
We go through every element of the input list and insert them in a sorted tree (minus the ones which were rolled back) (plus new ones for commits). So the insertion is done in o(n log(n))
I believe that since the input is already sorted, we can achieve that in o(n)
Some tests are still failing, so I still have a lot of check code here and there that will go away once I figure out why.

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST FAILED

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST FAILED

**Pull request closed without merging**
