### PR TITLE
DB-9682 SELECT on external table needs to check number of columns returned (2.8)

### PR DESCRIPTION
**Pull request by martinrupp**
also DB-7348 truncate CHAR/VARCHAR from external tables

### CODE REVIEW

**Comment by martinrupp** [comment]
jenkins please test branch @cdh5.12.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1134/

**Comment by martinrupp** [comment]
jenkins please test branch @cdh5.12.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1146/

**Comment by martinrupp** [comment]
jenkins please test branch @cdh5.12.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1151/

**Comment by martinrupp** [comment]
jenkins please test branch @cdh5.12.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1168/

**Comment by martinrupp** [comment]
jenkins please test branch @cdh5.12.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1190/

**Comment by martinrupp** [comment]
needs rebase

**Comment by martinrupp** [comment]
jenkins please test branch @cdh5.12.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1198/

**Comment by martinrupp** [comment]
sporadics

**Pull request merged**
