### PR TITLE
SPLICE-2129: Setting Olap Server external to false in Splice Test Platform.

### PR DESCRIPTION
**Pull request by stpabhi**

### CODE REVIEW

**Comment by jyuanca** [comment]
@stpabhi Why set olap server external to false by default.

**Comment by stpabhi** [comment]
@jyuanca Only in the test platform. External Olap server is broken in SpliceTestPlatform. I can’t get splice up and running with it.

**Comment by jyuanca** [comment]
@stpabhi Can you provide more info how it failed? It works for me.

**Comment by stpabhi** [comment]
@jyuanca Unfortunately, I didn't save my log and it's working now. Closing PR and JIRA.

**Pull request closed without merging**
