### PR TITLE
DB-9651 Fix spark scan issue with partial rows during flush

### PR DESCRIPTION
**Pull request by arnaud-splice**
During Spark scan, flushing the mem store would prevent us from
completing the scan of a specific row.
That could be one of the following reasons::
 - the row was partly in the mem store, partly in hfiles and we only
    read the memstore part
 - the memstore scan returned a partial row

This fix introduces a buffer row, that is only returned once we are sure
that it is complete. If a flush happens, we ditch the buffer and we
scan this row from scratch

This PR reverts DB-9449 as the new solution fixes both DB-9449 and DB-9651

### CODE REVIEW

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
