### PR TITLE
make SelectTimeTravelIT run on HBase profiles only.

### PR DESCRIPTION
**Pull request by hatyo**

### CODE REVIEW

**Review by ipraznik-splice — APPROVED** [review]

**Comment by ipraznik-splice** [comment]
jenkins please test branch @mem,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1807/

**Review by ascend1 — APPROVED** [review]

**Comment by ipraznik-splice** [comment]
jenkins please test branch @mem,skipTestsLongerThan2Minutes

**Review by arnaud-splice — APPROVED** [review]

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
