### PR TITLE
DB-11897 CTRL+C exit sqlshell if no query running

### PR DESCRIPTION
**Pull request by martinrupp**
## Short Description
CTRL+C now exits sqlshell if no query is running.

## How to test
open sqlshell, enter some characters, hit Ctrl+C. sqlshell should terminate.

### CODE REVIEW

**Review by hatyo — APPROVED** [review]
Thanks Martin! this PR really improves sqlshell usability.

**Review by arnaud-splice — APPROVED** [review]

**Comment by martinrupp** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2828/

**Review by carolp-503 — APPROVED** [review]
+1

**Comment by martinrupp** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2837/

**Comment by martinrupp** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
