### PR TITLE
DB-10183 Support NEXTVAL syntax for sequences 

### PR DESCRIPTION
**Pull request by arnaud-splice**

### CODE REVIEW

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Review by yxia92 — APPROVED** [review]
+1

**Review by ascend1 — APPROVED** [review]

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by carolp-503 — APPROVED** [review]
+1

**Review by dgomezferro — APPROVED** [review]

**Pull request merged**
