### PR TITLE
DB-9519 NSDS Time Support

### PR DESCRIPTION
**Pull request by jpanko1**

### CODE REVIEW

**Comment by jpanko1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1739/

**Review by jyuanca — CHANGES_REQUESTED** [review]
modifyRdd and schemaString are duplicated for all spark versions. Please refactor them out to some platform-independent module.

**Comment by jpanko1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1832/

**Comment by jpanko1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1833/

**Comment by jpanko1** [comment]
> modifyRdd and schemaString are duplicated for all spark versions. Please refactor them out to some platform-independent module.

Refactored in commits https://github.com/splicemachine/spliceengine/pull/4334/commits/ad726956cb24937d1fa14a786c32789ecbd6ae9d and https://github.com/splicemachine/spliceengine/pull/4334/commits/144d34c3a20e843de9da12e1b6e6dd306079f3be .

**Comment by jpanko1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by jyuanca — APPROVED** [review]

**Review by msirek — APPROVED** [review]

**Pull request merged**
