### PR TITLE
DB-12097 better SQL errors (3.1)

### PR DESCRIPTION
**Pull request by martinrupp**
## Short Description
improve error messages with more detailed description what's wrong with the SQL

## Example
SQL with errors:
```
CREATE TABLE MY_TABLE (
L_ORDERKEY BIGINT NOT NULL,
L_PARTKEY INTEGER NOT DECIMAL,
L_SUPPKEY INTEGER NOT NULL,
L_LINENUMBER INTEGER NOT NULL,
L_QUANTITY DECIMAL(15,2),
L_EXTENDEDPRICE DECIMAL(15,2),
L_DISCOUNT DECIMAL(15,2)
);
```

Error Message before

```
ERROR 42X01: Syntax error: Encountered "DECIMAL" at line 3, column 23.
```

New Error Message

```
ERROR 42X01: Syntax error: Encountered "DECIMAL" at line 3, column 23.
Was expecting:
    "null" ...
    
1: CREATE TABLE MY_TABLE (
2: L_ORDERKEY BIGINT NOT NULL,
3: L_PARTKEY INTEGER NOT DECIMAL,
                         ^^^^^^^---------
4: L_SUPPKEY INTEGER NOT NULL,
5: L_LINENUMBER INTEGER NOT NULL,
6:L_QUANTITY DECIMAL(15,2),
```

### CODE REVIEW

**Comment by martinrupp** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by cloudspliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/3205/

**Review by carolp-503 — APPROVED** [review]
Approved for 3.1

**Comment by msirek** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by cloudspliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
