### PR TITLE
SPLICE-2125 Remove hadoop/hbase dependencies from core modules

### PR DESCRIPTION
**Pull request by dgomezferro**
Changes summary:

1. Removed unused code from Datatypes
  1.1 encodedKeyLength() 
  1.2 encodeIntoKey(PositionedByteRange builder, Order order)  
  1.3 decodeFromKey(PositionedByteRange builder)
2. Wrapped UserGroupInformation in DRDAConnThread into a dynamically loaded object implemented in the hbase_sql module
3. Removed usages of org.apache.hadoop.hbase.util.Bytes from splice_machine module

### CODE REVIEW

**Comment by wtang16** [comment]
@dgomezferro Can you prepare a 2.5 branch with your code? Due to it's scale of change, it's best that we run full regression tests on it.

**Comment by dgomezferro** [comment]
@wtang16 I created a build: http://206.225.8.98:8080/job/spliceengine-branch/job/spliceengine-branch/904/default/

**Comment by wtang16** [comment]
@dgomezferro build 904 failed.

**Comment by dgomezferro** [comment]
@wtang16 I'm not sure why it appears red on jenkins but it succeeded, you can check the console: http://206.225.8.98:8080/job/spliceengine-branch/job/spliceengine-branch/904/default/console
And the artifacts were generated: http://206.225.8.98:8080/job/spliceengine-branch/job/spliceengine-branch/904/default/artifact/assembly/target/parcels/

**Comment by wtang16** [comment]
You are right @dgomezferro. It's a strange behavior from Jenkins. But no issues for your commit. Thanks!

**Pull request merged**
