### PR TITLE
DB-8104 Fix date formats which have no separator characters.

### PR DESCRIPTION
**Pull request by msirek**
SQL such as 'VALUES TO_DATE('19000101','yyyyMMdd');' errors out when it should not.
Also, use of date format strings without separators in import statements similarly errors out when it should not.

See [DB-8104](https://splicemachine.atlassian.net/browse/DB-8104?oldIssueView=true)

### CODE REVIEW

**Comment by msirek** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST FAILED

**Comment by msirek** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST FAILED

**Comment by msirek** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
