### PR TITLE
SPLICE-1905: [External Tables]: Failed to run select query from partitioned external table in case of NULL presence.

### PR DESCRIPTION
**Pull request by stpabhi**

### CODE REVIEW

**Comment by jyuanca** [comment]
Please add some ITs

**Comment by stpabhi** [comment]
@jyuanca Added ITs for all the Datatypes. please review it.

**Comment by jyuanca** [comment]
@stpabhi please port to 2.5 and 2.6 branches if applicable.

**Comment by stpabhi** [comment]
@jyuanca Ok. As 2.5 doesn't support ORC yet will submit pull request for 2.6

**Pull request merged**
