### PR TITLE
DB-12183 Support Spark 3.1.1

### PR DESCRIPTION
**Pull request by ipraznik-splice**
## Short Description
Adds the support of spark 3.1.1

## Long Description
To keep the support of spark 3.0.1 for the existing clusters, the new profile dbaas3.1 is created. 
The profile dbaas3.1 has new dependencies for spark 3.1.1
Following API changes have been adjusted in versioned folders:
- SparkSqlParser(new SQLConf) is changed to SparkSqlParser()
- JdbcUtils.createTable(conn, df, jdbcOptions) changed to createTable(conn, table, df.schema, true, jdbcOptions) 

## How to test
No difference in execution between dbaas3.1 and dbaas3.0, but there are some important fixes in spark 3.1.1, for example, reading parquet rdd does not fail with  java.io.IOException: java.util.NoSuchElementException: None.get any more (DB-11033)

- local testing: start a standalone cluster ./start-splice-cluster -p dbaas3.1
- on jenkins: jenkins please test branch @dbaas3.1,skipTestsLongerThan2Minutes

### CODE REVIEW

**Comment by ipraznik-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by cloudspliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/3116/

**Comment by ipraznik-splice** [comment]
jenkins please test branch @dbaas3.0,skipTestsLongerThan2Minutes

**Comment by cloudspliceci** [comment]
TEST SUCCEEDED +1

**Review by bklo94 — APPROVED** [review]

**Comment by ipraznik-splice** [comment]
jenkins please test branch @dbaas3.1,skipTestsLongerThan2Minutes

**Comment by cloudspliceci** [comment]
TEST SUCCEEDED +1

**Review by martinrupp — CHANGES_REQUESTED** [review]
please adjust description

**Comment by ipraznik-splice** [comment]
jenkins please test branch @dbaas3.1,skipTestsLongerThan2Minutes

**Comment by cloudspliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/3163/

**Comment by ipraznik-splice** [comment]
jenkins please test branch @dbaas3.1,skipTestsLongerThan2Minutes

**Comment by ipraznik-splice** [comment]
jenkins please test branch @dbaas3.1,skipTestsLongerThan2Minutes

**Review by martinrupp — APPROVED** [review]

**Comment by cloudspliceci** [comment]
TEST SUCCEEDED +1

**Review by bklo94 — APPROVED** [review]

**Comment by ipraznik-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Review by jyuanca — APPROVED** [review]

**Comment by cloudspliceci** [comment]
TEST SUCCEEDED +1

**Review by carolp-503 — APPROVED** [review]
+1

**Pull request merged**
