### PR TITLE
SPLICE-2179 Upgrade hppc library to 0.7.2.

### PR DESCRIPTION
**Pull request by stpabhi**

### CODE REVIEW

**Comment by dgomezferro** [comment]
@stpabhi is this the only change needed to work with Spark 2.3? Have you tested it?

**Comment by stpabhi** [comment]
@dgomezferro Will fix mem_storage. There are couple other fixes. Please refer to this umbrella JIRA.
https://splice.atlassian.net/browse/SPLICE-2178

**Comment by stpabhi** [comment]
@dgomezferro Yes, I have tested it. I have a working cluster running spark2.3.0.cloudera2 with SpliceMachine 1819

**Comment by stpabhi** [comment]
@dgomezferro fixed mem storage. Please review

**Comment by dgomezferro** [comment]
Looks good, thanks!

**Comment by stpabhi** [comment]
@wtang16 Can we merge this?

**Comment by wtang16** [comment]
@stpabhi now that we have 2 approvals, this PR can be merged to master. But this one is part of a bigger effort to support Spark 2.3. If we use 0.7.2 version of hppc, will it work for Spark 2.2?

**Comment by stpabhi** [comment]
@wtang16 It should work because spark2.2 doesn't use hppc and I couldn't find it in the classpath. I haven't tested it yet. Would you be able to test?

**Comment by jyuanca** [comment]
@stpabhi If the changes apply to branch 2.5 and 2.7, can you please backport?

**Comment by stpabhi** [comment]
@jyuanca #2004 #2007

**Pull request merged**
