### PR TITLE
DB-10917 Properly support [var]char(<[var]char for bit data>, <len>) 

### PR DESCRIPTION
**Pull request by arnaud-splice**

### CODE REVIEW

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Review by martinrupp — APPROVED** [review]
coool

**Review by dgomezferro — APPROVED** [review]
Really like `typeof`, nice addition @arnaud-splice !

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2058/

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Review by carolp-503 — APPROVED** [review]
+1

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
