### PR TITLE
DB-7885 Add cdh5.16.1 support (2.7)

### PR DESCRIPTION
**Pull request by bklo94**

### CODE REVIEW

**Comment by bklo94** [comment]
jenkins please test branch @cdh5.16.1

**Comment by spliceci** [comment]
TEST FAILED

**Comment by bklo94** [comment]
jenkins please test branch @cdh5.16.1

**Comment by bklo94** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
