### PR TITLE
DB-10326 Switch "AT" from reserved to non-reserved keyword 

### PR DESCRIPTION
**Pull request by arnaud-splice**

### CODE REVIEW

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by ipraznik-splice — APPROVED** [review]

**Review by dgomezferro — CHANGES_REQUESTED** [review]
Can we add a test case?

**Comment by arnaud-splice** [comment]
> Can we add a test case?

Done

**Review by yxia92 — APPROVED** [review]
+1

**Pull request merged**
