### PR TITLE
DB-11138 remove unused method parameter and use SanityManager checks.

### PR DESCRIPTION
**Pull request by hatyo**
## Short Description
This PR attempts to fix a sporadic that might be caused by unboxing null value. Also, we add `SanityManager` checks to document preconditions in order to get a clear error message should the sporadic appear again.

### CODE REVIEW

**Comment by hatyo** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by cloudspliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/3384/

**Review by msirek — APPROVED** [review]

**Comment by hatyo** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by cloudspliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/3394/

**Comment by hatyo** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Review by ascend1 — APPROVED** [review]

**Comment by cloudspliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/3399/

**Review by carolp-503 — APPROVED** [review]
+1

**Pull request merged**
