### PR TITLE
DB-8041 Use average rows per value as estimation for qualified row fo…

### PR DESCRIPTION
**Pull request by yxia92**
…r equality condition of type "col=expr"

### CODE REVIEW

**Comment by yxia92** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST FAILED

**Comment by yxia92** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
