### PR TITLE
SPLICE-466 Make with data the default for create table as (Oracle style)

### PR DESCRIPTION
**Pull request by jleach4**
Adhering to Oracle Syntax 2.0 commit.

### CODE REVIEW

**Comment by jyuanca** [comment]
+1

**Comment by dgomezferro** [comment]
Should we change this behaviour mid-release in 2.0?

**Comment by ammolitor** [comment]
@dgomezferro, the docs already indicate this behavior. 

http://doc.splicemachine.com/SQLReference/Statements/CreateTable.html

**Comment by dgomezferro** [comment]
@ammolitor Thanks, this makes sense then!
+1

**Pull request merged**
