### PR TITLE
DB-6871: incremental backup improvements(2.7)

### PR DESCRIPTION
**Pull request by jyuanca**
1. keeps track of compaction and split
2. do not block on flush

### CODE REVIEW

**Comment by jyuanca** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by MurrayBrown** [comment]
Per Daniel's suggestion, I think this was not merged in december.

Do we have a test in-flight to prove out incremental backup against the master snapshot build? I guess I am asking, what do we need to do to resolve this and get this PR either in (or out)?

**Comment by jyuanca** [comment]
This failed Jenkins build. I'll close it and investigate.

**Pull request closed without merging**
