### PR TITLE
DB-8382 use tablenumber to find relevant columns

### PR DESCRIPTION
**Pull request by yxia92**
Please see [DB-8382](https://splicemachine.atlassian.net/browse/DB-8382?oldIssueView=true) for analysis.

### CODE REVIEW

**Comment by yxia92** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST FAILED

**Comment by yxia92** [comment]
jenkins please retest branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST FAILED

**Comment by yxia92** [comment]
jenkins please retest branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
