### PR TITLE
DB-8200 fix NPE and wrong result for nested loop join with UNION operation as right table

### PR DESCRIPTION
**Pull request by yxia92**
A second submission for DB-8200. This has the additional fix to address the intermittent wrong result exposed in the IT. For more details of the problem and fix, please see [this comment in DB-8200](https://splicemachine.atlassian.net/browse/DB-8200?focusedCommentId=61038&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-61038).

### CODE REVIEW

**Comment by yxia92** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST FAILED

**Comment by bklo94** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
