### PR TITLE
DB-9828 Respect SET_PURGE_DELETED_ROWS in hbase compactions

### PR DESCRIPTION
**Pull request by arnaud-splice**

### CODE REVIEW

**Comment by dgomezferro** [comment]
@arnaud-splice can you schedule a jenkins test run?

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1053/

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
