### PR TITLE
DB-8480 do not flatten non-correlated scalar aggregate subquery

### PR DESCRIPTION
**Pull request by yxia92**
Please see [DB-8480](https://splicemachine.atlassian.net/browse/DB-8480) for details.
There is an IT update in ee branch, please review the corresponding [PR#378](https://github.com/splicemachine/spliceengine-ee/pull/378)

### CODE REVIEW

**Comment by yxia92** [comment]
jenkins please test branch @cdh5.14.0

**Comment by spliceci** [comment]
TEST FAILED

**Comment by yxia92** [comment]
jenkins please test branch @cdh5.14.0

**Comment by spliceci** [comment]
TEST FAILED

**Comment by yxia92** [comment]
@carolp-503 Yes, I tested tpch1 on my local system, q22's performance number gets back to that before DB-8024.  Before DB-8024, we flatten the aggregate subquery in q22 with a nested loop join. With tpch at scale 1, the current plan not to flatten the subquery does not show much performance advantage over the nested loop join plan, but as the scale goes up, the advantage should become more visible.
Also q15 has a similar plan change as q22.

**Comment by yxia92** [comment]
jenkins please test branch @cdh5.14.0

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
