### PR TITLE
DB-7885 Add cdh5.16.1 support

### PR DESCRIPTION
**Pull request by bklo94**
Has an associated ee repo PR with some changes

### CODE REVIEW

**Comment by bklo94** [comment]
jenkins please test branch @cdh5.16.1

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by bklo94** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
