### PR TITLE
DB-6356: forward port decoupling changes to master

### PR DESCRIPTION
**Pull request by snowspeeder**
Forward port the spark decoupling and related changes to the master by Oleg and me. Thanks to Oleg for resolving the parquet jar untangling issue.

### CODE REVIEW

**Comment by jleach4** [comment]
Please add all platforms for Spark.

**Comment by snowspeeder** [comment]
Added splice_spark module for other platforms as well.

**Comment by snowspeeder** [comment]
After reverting splice_spark adapter for mapr and hdp, all IT runs for CDH and mapr are good, please review and merge this PR soon. DB-6454 is open to track spark-adapter IT issues for mapr, and another Jira will be open for hdp ITs by Oleg. Thanks!

**Comment by wtang16** [comment]
Oleg's JIRA for HDP is DB-6456.

**Pull request merged**
