### PR TITLE
 SPLICE 741

### PR DESCRIPTION
**Pull request by jfilali**
Use Kryo pools in result streamer   stream listener
 Added Kryo Pool master
 This version added  ThreadLocal to avoid race condition with multiple handlers used with Netty.
 It should now use  different kryo objects by thread basis and then the kryo object will be return when the thread close and perform a clean of its ThreadLocal

### CODE REVIEW

**Comment by jfilali** [comment]
wait for it, need to make change , thanks to Scott.

**Comment by jfilali** [comment]
@scottfines please look at it now

**Comment by jeffcunningham** [comment]
+1, nice!

**Comment by genedavis** [comment]
+1

**Comment by scottfines** [comment]
+1 from me. Let's merge this into 2.0 as well; can you create a second PR against branch-2.0 and assign it to me?

**Pull request merged**
