### PR TITLE
DB-8846 Update Documentation CDH 6.3.0 for external Table support

### PR DESCRIPTION
**Pull request by martinrupp**
Java Configuration Options for HBase Master need an additional
-Dsplice.olapServer.classpath=/opt/cloudera/parcels/CDH/lib/hive/lib/*

/opt/cloudera/parcels/CDH/lib/hive/lib/ has hive-orc.jar, which contains e.g.
org/apache/orc/OrcConf.class that was a problem resolving.
Error message before was
java.lang.NoClassDefFoundError: org/apache/orc/OrcConf

### CODE REVIEW

**Comment by dgomezferro** [comment]
Do we need to apply the same change to the HDP installer in service_advisor.py ?

**Comment by martinrupp** [comment]
hm i guess... there's two files

1.  https://github.com/splicemachine/spliceengine/blob/ef5a96ae70e00c39dcb3ed6485488d6f8e2b5b66/assembly/hdp3.1.0/src/main/resources/common-services/SPLICEMACHINE/2.5.1/service_advisor.py#L293

i guess at line 293

2. https://github.com/splicemachine/spliceengine/blob/ef5a96ae70e00c39dcb3ed6485488d6f8e2b5b66/assembly/hdp3.1.0/build/var/lib/ambari-server/resources/common-services/SPLICEMACHINE/2.5.1/service_advisor.py
Not sure where to add it there. There's some config lines in 104... not sure.

How can we test this?

**Comment by jyuanca** [comment]
@martinrupp You can follow [this](https://splicemachine.atlassian.net/wiki/spaces/PD/pages/313524225/How+to+build+RPM+packages+for+HDP+2.6.3+and+deploy+it+on+cluster) to deploy a hdp3.1.0 rpm to test. The documentation is for hdp2.6.3, but hdp3.1.0 is very similar

**Comment by martinrupp** [comment]
had to do another commit on top fixing something https://github.com/splicemachine/spliceengine/pull/3515

**Pull request merged**
