### PR TITLE
DB-11207 Support creation of table LIKE other table

### PR DESCRIPTION
**Pull request by arnaud-splice**
### Description:
This ticket introduces a new way to create tables:

```
create table base (a INT);
CREATE TABLE T1 LIKE base; 

show create table t1;
DDL
---
CREATE TABLE "SPLICE"."T1" (
"A" INTEGER
) ;
```

The newly created table will have the same column structure as the original one. Nullability and default values will also be the same as for the original one.
As DB2, we do not reproduce constraints, primary keys, etc. Only the column structure is ported to the new table

 

This is also supported when creating temporary tables:

```
DECLARE GLOBAL TEMPORARY TABLE T2 LIKE base;

show create table t2;
DDL
---
CREATE LOCAL TEMPORARY TABLE "SPLICE"."T2" (
"A" INTEGER
) ;
```
### Testing:
This was tested with temporary and non-temporary tables, with nullable and non nullable columns, with default (empty or not) values for columns.

We also tested that constraints are not carried over from base table to new table.

### CODE REVIEW

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2466/

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2468/

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by martinrupp — APPROVED** [review]

**Review by ipraznik-splice — APPROVED** [review]

**Review by dgomezferro — APPROVED** [review]

**Pull request merged**
