### PR TITLE
DB-6234: add more logging (2.5)

### PR DESCRIPTION
**Pull request by jyuanca**

### CODE REVIEW

**Comment by snowspeeder** [comment]
nice to have spark22-2.5 branch PR

**Comment by jyuanca** [comment]
You can rebase spark22-2.5 branch to pick up the changes once it is in

**Comment by snowspeeder** [comment]
Spark22 branch will be here for some time, do you want me to take care of
rebase for every commit. It would be better to open PR on this branch and
see regression runs on spark22 branch just like other branches we do.

**Comment by jyuanca** [comment]
You can rebase once for a while. It's not a good practice to send an extra PR for every commit.

**Comment by snowspeeder** [comment]
Ok, I will be the guardian of this branch and do the periodic sync. All, no
need to open a searate PR on spark22-2.5 branch.

**Pull request merged**
