### PR TITLE
DB-10587 Resolve timed out transactions properly (2.8)

### PR DESCRIPTION
**Pull request by dgomezferro**

### CODE REVIEW

**Comment by dgomezferro** [comment]
jenkins please test branch @cdh5.14.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1802/

**Comment by dgomezferro** [comment]
jenkins please test branch @cdh5.14.0,skipTestsLongerThan2Minutes

**Review by carolp-503 — APPROVED** [review]
Approved for 2.8

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1812/

**Comment by ipraznik-splice** [comment]
jenkins please test branch @cdh5.14.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
