### PR TITLE
SPLICE-1452 correct cardinality estimation when there is missing part…

### PR DESCRIPTION
**Pull request by yxia92**
…ition stats

Port the change to master branch.

### CODE REVIEW

**Comment by snowspeeder** [comment]
There is a missing IT, which I believe you're fixing it. I'd suggest port both the changes together to master then.

**Comment by yxia92** [comment]
The IT hasn’t been fixed yet and the test case is currently ignored, do you still want me to port to master?

Thanks.

**Comment by snowspeeder** [comment]
I’d wait until IT is fixed unless this is very urgent change reqd.

**Comment by yxia92** [comment]
Sure. I’ll see if I can re-design the IT that can give consistent behavior.

**Comment by yxia92** [comment]
@snowspeeder, I've fixed the unit test case to give consistent result.

**Comment by snowspeeder** [comment]
Thanks @yxia92

**Comment by OlegMazurov** [comment]
@yxia92, in PR#696 for 2.5 you changed StatsUsageIT.java. Here you add CostEstimationIT.java but leave StatsUsageIT.java intact. Changes to StoreCostControllerImpl.java are identical in both PRs. Why such inconsistency?

**Comment by yxia92** [comment]
@Oleg,

The fix of SPLICE-1452 was first shipped to 2.5, but then its unit test which was added to StatsUsageIT.java was commented out due to non-deterministic behavior, also this test case fails under the mem platform(The test case needs a table split call which does not work for mem database). In the pull request for 2.6, I put the test case into a separate file which will only be called for hbase platform, and also modify the unit test case so that it will behave consistently for repeated runs.
I’m making a pull request to ship the test case to 2.5 and remove the original test case from StatsUsageIT.
Sorry for the confusion.

**Comment by OlegMazurov** [comment]
@yxia92 thanks for the explanation

**Pull request merged**
