### PR TITLE
DB-11224 Don't set exclude null/default flags of an index when they have no effect (3.1)

### PR DESCRIPTION
**Pull request by ascend1**
See https://github.com/splicemachine/spliceengine/pull/5392

### CODE REVIEW

**Comment by ascend1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by carolp-503 — APPROVED** [review]
Approved for 3.1

**Comment by ascend1** [comment]
jenkins please test branch @cdh6.3.0

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2795/

**Comment by ascend1** [comment]
jenkins please test branch @cdh6.3.0

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
