### PR TITLE
SPLICE-2241 Cleanup Spark Adapter docs

### PR DESCRIPTION
**Pull request by dgomezferro**

### CODE REVIEW

**Comment by wb14123** [comment]
I use this command to described in JIRA:

```
cd splice_spark
mvn compile scala:doc -Pcdh5.8.3
```
But it failed with


> [ERROR] Failed to execute goal on project splicemachine-cdh5.8.3-2.2.0.cloudera2_2.11: Could not resolve dependencies for project com.splicemachine:splicemachine-cdh5.8.3-2.2.0.cloudera2_2.11:jar:2.8.0.1836-SNAPSHOT: The following artifacts could not be resolved: com.splicemachine:hbase_storage-cdh5.8.3:jar:2.8.0.1836-SNAPSHOT, com.splicemachine:hbase_sql-cdh5.8.3:jar:2.8.0.1836-SNAPSHOT, com.splicemachine:hbase_pipe
> line-cdh5.8.3:jar:2.8.0.1836-SNAPSHOT: Failure to find com.splicemachine:hbase_storage-cdh5.8.3:jar:2.8.0.1836-SNAPSHOT in https://repositor
> y.cloudera.com/artifactory/cloudera-repos/ was cached in the local repository, resolution will not be reattempted until the update interval of cloudera has elapsed or updates are forced -> [Help 1]


Maybe need to run `mvn install` first?

**Comment by jyuanca** [comment]
@dgomezferro Can you resolve conflicts?

**Comment by OlegMazurov** [comment]
I see changes for  splice_spark/src/main/spark2.2/com/splicemachine/spark/splicemachine/SplicemachineContext.scala
but none for spark2.1/2.3.
Shouldn't they be maintained as well?

**Comment by dgomezferro** [comment]
@OlegMazurov applied changes to Spark 2.3, ready for merging

**Comment by dgomezferro** [comment]
jenkins please test branch @hdp2.6.5

**Comment by spliceci** [comment]
TEST FAILED

**Comment by dgomezferro** [comment]
jenkins please test branch @hdp2.6.5

**Comment by spliceci** [comment]
TEST FAILED

**Comment by dgomezferro** [comment]
jenkins please test branch @hdp2.6.5

**Comment by spliceci** [comment]
TEST FAILED

**Comment by dgomezferro** [comment]
jenkins please test branch @cdh5.13.0

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by jaceklaskowski** [comment]
> jenkins please test branch @cdh5.13.0

Just watching all the "please test"s and am wondering why you chose `@cdh5.13.0` while others `cdh5.13.3`? Moreover why is `cdh5.8.3` profile the default for `./start-splice-cluster`? We should really have a README on it, shouldn't we? (I myself really need it)

**Comment by OlegMazurov** [comment]
@jaceklaskowski cdh5.13.0 was initially introduced as the only profile configured to use Spark 2.3, which is essential to this PR. We now have cdh5.12.2-2.3 that is preferable for that purpose.
The default in ./start-splice-cluster is of little importance for developers. Feel free to update it to something more up-to-date, say 5.12.2

**Comment by jaceklaskowski** [comment]
If I may "hijack" the thread, why is that _"The default in ./start-splice-cluster is of little importance for developers"_? What's the proper way then?

**Comment by dgomezferro** [comment]
@jaceklaskowski I wouldn't say is of little importance, I think Oleg just meant it's easy to choose the profile you want. I agree having a saner default makes sense, I opened a PR updating the default to cdh5.14.0

**Pull request merged**
