### PR TITLE
DB-9193 Spark 2.4 support for Mapr6.1

### PR DESCRIPTION
**Pull request by bklo94**
- Added Spark2.4.4 and Hbase1.1.13 files.
- Move around some files and split them into their respective hbase/spark folders since there are incompatible src/test files depending on the spark version that is pulled down. 
- Added MapR filter in assembly to create the correct hbase configuration file.

### CODE REVIEW

**Comment by bklo94** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by jaceklaskowski** [comment]
I'm curious why the change was tested against `@cdh5.12.2` not mapr61?

**Comment by bklo94** [comment]
The automated jenkins hook testing only supports/completes against hdfs platforms (i.e hdp/cdh). Unfortunately mapr uses maprfs which isn't implement the same way. To test our mapr, there is a separate test framework to point towards a remote cluster.
Since there was changes to cdh related files I asked jenkins to test against the cdh platform.

**Pull request merged**
