### PR TITLE
SPLICE-579 Implement JDBC cancel() operation

### PR DESCRIPTION
**Pull request by dgomezferro**

### CODE REVIEW

**Comment by jyuanca** [comment]
jenkins please test branch @cdh5.13.3

**Comment by spliceci** [comment]
TEST FAILED

**Comment by jyuanca** [comment]
jun [7:30 PM]
I happened to run some spark adapter tests(DefaultSourceTest) on this branch.  got some errors
Caused by: java.lang.NullPointerException
    at java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1106)
    at java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1097)
    at com.splicemachine.derby.iapi.sql.execute.OperationManagerImpl.unregisterOperation(OperationManagerImpl.java:50)
    at com.splicemachine.derby.impl.sql.execute.operations.SpliceBaseOperation.open(SpliceBaseOperation.java:284)
    at com.splicemachine.db.impl.sql.GenericPreparedStatement.executeStmt(GenericPreparedStatement.java:363)
    at com.splicemachine.db.impl.sql.GenericPreparedStatement.execute(GenericPreparedStatement.java:283)
    at com.splicemachine.db.impl.jdbc.EmbedStatement.executeStatement(EmbedStatement.java:1259)

**Comment by dgomezferro** [comment]
jenkins please test branch @cdh5.13.3

**Comment by spliceci** [comment]
TEST FAILED

**Comment by dgomezferro** [comment]
jenkins please test branch @cdh5.13.3

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by dgomezferro** [comment]
@jyuanca thanks for the testing! Fixed the broken tests and pushed a fix.

**Pull request merged**
