### PR TITLE
Do not merge.  For running ITs only.

### PR DESCRIPTION
**Pull request by msirek**

### CODE REVIEW

**Comment by msirek** [comment]
jenkins please test branch @cdh6.3.0

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1950/

**Comment by msirek** [comment]
jenkins please test branch @cdh6.3.0

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1951/

**Pull request closed without merging**
