### PR TITLE
DB-7748 Restore old behavior of import date format

### PR DESCRIPTION
**Pull request by msirek**
This PR reverts an import date format behavior change introduced by SPLICE-2264.  
A date format of yyyy-MM-dd will now accept dates with single-digit month and day once again,
for example 2011-1-21, 2001-08-6, 2012-6-8.

For more details please see:  [DB-7748](https://splicemachine.atlassian.net/browse/DB-7748?focusedCommentId=58738&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-58738)

### CODE REVIEW

**Comment by msirek** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST FAILED

**Comment by msirek** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
