### PR TITLE
DB-11234 Fix potential memory leak caused by tc.openConglomerate 

### PR DESCRIPTION
**Pull request by arnaud-splice**
**Description**

openConglomerate returns a ConglomerateController that implements AutoCloseable. Some calls to openConglomerate were neither surrounded by a try-with-resources, nor with a try … finally {close} and could lead / have lead to memory leaks.

I modified all occurrences to properly use try-with-resources

**Testing**

No additional testing was conducted. If ITs pass, I consider this tested.

### CODE REVIEW

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by hatyo** [comment]
PR looks good, it would be nice to write some explanation in the commit message about what's exactly is done (e.g. use try-with-resource in more places).

**Review by hatyo — APPROVED** [review]

**Review by ipraznik-splice — APPROVED** [review]

**Review by dgomezferro — APPROVED** [review]
Nice cleanup!

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by carolp-503 — APPROVED** [review]
+1

**Comment by hatyo** [comment]
After some investigation we found the a sporadically failing test has caused a build failure which is not related to this PR.

**Pull request merged**
