### PR TITLE
SPLICE-82 Remove ThreadLocal and clearBroadcastedOperation() from SparkDataSetProcessor

### PR DESCRIPTION
**Pull request by OlegMazurov**
Straightforward.

### CODE REVIEW

**Comment by OlegMazurov** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST FAILED

**Comment by OlegMazurov** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST FAILED

**Comment by OlegMazurov** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by MurrayBrown** [comment]
This looks so deceptively simple, that I feel that I am missing something. I've looked at it and I like it, but I feel unqualified to peer review ?

**Comment by OlegMazurov** [comment]
Note that _ThreadLocal_ was not declared **static** so each instance of _SparkDataSetProcessor_ used its own copy of _BroadcastedActivation_ (which would be available only on the originating thread but that seemed to be OK). Given that, it's really straightforward.

**Pull request merged**
