### PR TITLE
SPLICE-2300 Native Spark transformation for PRs that only map columns

### PR DESCRIPTION
**Pull request by dgomezferro**
See https://splice.atlassian.net/browse/SPLICE-2300 for benchmark details.

### CODE REVIEW

**Comment by dgomezferro** [comment]
jenkins please retest branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST FAILED

**Comment by dgomezferro** [comment]
jenkins please retest branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST FAILED

**Comment by dgomezferro** [comment]
jenkins please retest branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST FAILED

**Comment by dgomezferro** [comment]
jenkins please retest branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
