### PR TITLE
DB-8138 Update trigger fix

### PR DESCRIPTION
**Pull request by msirek**
Do not merge this PR!
For code review only.

### CODE REVIEW

**Comment by msirek** [comment]
jenkins please test branch @cdh5.13.3

**Comment by spliceci** [comment]
TEST FAILED

**Comment by msirek** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST FAILED

**Comment by msirek** [comment]
jenkins please test branch @cdh5.13.3

**Comment by spliceci** [comment]
TEST FAILED

**Comment by jyuanca** [comment]
jenkins please test branch @cdh5.13.3

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request closed without merging**
