### PR TITLE
SPLICE-1399 Fixed typo in error message

### PR DESCRIPTION
**Pull request by tjo7**
Fixed Typo and Added Test

### CODE REVIEW

**Comment by bklo94** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST FAILED

**Comment by bklo94** [comment]
jenkins please test branch @cdh5.12.2

**Comment by jyuanca** [comment]
@tjo7 Jenkins needs a matching branch(SPLICE-1399) on spliceengine-ee to run ITs. @bklo94 created one for you and kicked off ITs again

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
