### PR TITLE
SPLICE-2119 Make dictionary cache size configurable

### PR DESCRIPTION
**Pull request by wb14123**

### CODE REVIEW

**Comment by wb14123** [comment]
@jyuanca I've add the comment to JIRA issue and in the source code. I think these properties will be used internal only. Do I need to change anything else?

**Comment by jyuanca** [comment]
@wb14123 You will need to handle token cache after DB-6727 is merged

**Comment by yxia92** [comment]
I think adding new database property does not require any additional logic for upgrade consideration, but it would be good to just test upgrade to confirm.

**Comment by wb14123** [comment]
@jyuanca Added token cache.

**Pull request merged**
