### PR TITLE
SPLICE-948 Intersect Error Not Implemented on the wrong case

### PR DESCRIPTION
**Pull request by jleach4**
We do not currently support  
intersect all,
 except all  
but we do support
 intersect,
 except.
This commit attempts to straighten that out.  Branch-2.0 version.

### CODE REVIEW

**Comment by genedavis** [comment]
Need Open Source header on SetOpOperationIT.java

**Comment by jleach4** [comment]
Header added to file.

**Comment by jyuanca** [comment]
+1

**Comment by dgomezferro** [comment]
+1

**Pull request merged**
