### PR TITLE
Merge Optimizer staging -> master

### PR DESCRIPTION
**Pull request by arnaud-splice**
## USE CREATE A MERGE COMMIT INSTEAD

This PR can be merged iff:
DB-11558 passes tests
DB-11622 gets 2 +1s and passes tests

### CODE REVIEW

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2630/

**Comment by msirek** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
