### PR TITLE
DB-11101 fix SHOW PRIMARY KEYS, add tests for sqlshell

### PR DESCRIPTION
**Pull request by martinrupp**

### CODE REVIEW

**Comment by martinrupp** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2215/

**Review by jyuanca — CHANGES_REQUESTED** [review]
Code change looks good. There is a test failure needs to be investigated

http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2215/testReport/junit/com.splicemachine.derby.utils/SqlshellIT/testDescribeTablePKs/

**Comment by martinrupp** [comment]
> Code change looks good. There is a test failure needs to be investigated

thanks, should be done now

**Review by jyuanca — APPROVED** [review]

**Comment by martinrupp** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Review by msirek — APPROVED** [review]

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by carolp-503 — APPROVED** [review]
+1

**Review by dgomezferro — APPROVED** [review]
Awesome IT @martinrupp !

**Pull request merged**
