### PR TITLE
DB-11234 Fix potential memory leak caused by tc.openConglomerate (3.0)

### PR DESCRIPTION
**Pull request by arnaud-splice**

### CODE REVIEW

**Review by carolp-503 — APPROVED** [review]
Approved for 3.0

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2467/

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
