### PR TITLE
DB-12085 Redo Fix isQualifier() for index conglomerates (3.1)

### PR DESCRIPTION
**Pull request by ascend1**
See https://github.com/splicemachine/spliceengine/pull/5505.

### CODE REVIEW

**Comment by ascend1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Review by arnaud-splice — APPROVED** [review]

**Comment by cloudspliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/3003/

**Review by carolp-503 — APPROVED** [review]
Approved for 3.1

**Comment by hatyo** [comment]
Two sporadic failures in:
    com.splicemachine.subquery.Subquery_Scalar_IT.subqueryWithSum
    com.splicemachine.backup.BackupSchemaIT.testSchemaBackupRestore
I will overrule Jenkins test validation and merge the PR.

**Pull request merged**
