### PR TITLE
SPLICE-1600: Fix SYSSOURCECODE integration test

### PR DESCRIPTION
**Pull request by jsoroka**
Left out an important commit during rebase for PR#652.

Also, PR#652 asked to have "create=true;" removed from IT JDBC URL, which was copied from Trigger_*_IT.java files, so I updated those as well.  https://github.com/splicemachine/spliceengine/pull/652#discussion_r113553243

### CODE REVIEW

**Comment by jyuanca** [comment]
Please squash them into one commit.

**Comment by jsoroka** [comment]
Squashed.

**Comment by jyuanca** [comment]
@jsoroka There are still 2 commits. Squash them in one. Thanks!

**Comment by jsoroka** [comment]
Woops, I see now.  Thank you.  Commits have been squashed.

**Pull request merged**
