### PR TITLE
DB-8190 DB-9604 Make Spark fetch and shuffle partitions configurable 

### PR DESCRIPTION
**Pull request by dgomezferro**
Same PR as https://github.com/splicemachine/spliceengine/pull/3668 with @jyuanca's fix for NSDS

Thanks @yxia92 and @jyuanca !

### CODE REVIEW

**Comment by dgomezferro** [comment]
jenkins please test branch @cdh6.3.0

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by dgomezferro** [comment]
jenkins please test branch @cdh6.3.0

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
