### PR TITLE
DB-12033 Multiple compilations of a prepared statement due to poor cache synchronization

### PR DESCRIPTION
**Pull request by OlegMazurov**
## Short Description
Fixed DataDictionaryCache.statementCache to do atomic "computeIfAbsent".

## Long Description
Multiple connections compiling identical statements would check DataDictionaryCache.statementCache to see if a prepared statement is already available, create new prepared statements if not and  add them to the cache. Only one wins, others would continue with compiling the statement to eventually throw away the result.
Also fixed unnecessarily complicated synchronization around prepared statements that reference session schema.

## How to test
Run TPC-C, verify if there are multiple compilations of identical SELECT/UPDATE/DELETE statements in the same region server.

### CODE REVIEW

**Comment by OlegMazurov** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by jyuanca — APPROVED** [review]

**Comment by OlegMazurov** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2887/

**Comment by OlegMazurov** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by arnaud-splice — APPROVED** [review]

**Review by ipraznik-splice — APPROVED** [review]

**Review by carolp-503 — APPROVED** [review]
+1

**Pull request merged**
