### PR TITLE
DB-10865 force statistics collection during analyze execution.

### PR DESCRIPTION
**Pull request by hatyo**
Previously, collection of table statistics of a schema was done lazily during streaming of results, i.e. whenever DRDA requests a new row of `analyze` result set we return a row pertaining one of the analyzed tables so far and we might trigger analyzing a new table assuming as long as we do not exceed `splice.statistics.collectSchemaStatisticsMaximumConcurrent` concurrent operations.

This is probably fine since the user normally wait for the results to arrive to consider the statement's execution complete, however if the user monitors active operations using `SYSCS_UTIL.SYSCS_GET_RUNNING_OPERATIONS` then some inconsistencies will be noticed, the reason is that `SYSCS_GET_RUNNING_OPERATIONS` reads information about running operation from a `OperationManager`, this manager has certain hooks for registration and de-registration of running queries that are put around a query's execution activity and not result streaming activity. Therefore `analyze` appears only for a short while as a running operation, although it might take minutes longer to finish execution to the behavior described above of collecting statistics lazily.

To fix this issue, we force collecting the statistics for all tables during the execution time of the `analyze` allowing us to report its activity correctly in `SYSCS_GET_RUNNING_OPERATIONS`.

Writing tests for this PR is not straightforward since it is not easy to easily observe this behavior without some API mocking and I leave it for QA to verify.

### CODE REVIEW

**Review by jpanko1 — APPROVED** [review]

**Review by msirek — APPROVED** [review]

**Comment by hatyo** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2527/

**Comment by hatyo** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2530/

**Review by carolp-503 — APPROVED** [review]
+1

**Comment by hatyo** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
