### PR TITLE
SPLICE-839 Set default handler for uncaught exceptions

### PR DESCRIPTION
**Pull request by dgomezferro**
Improve logging in case an uncaught exception is thrown

### CODE REVIEW

**Comment by dgomezferro** [comment]
I'm not sure that's the best place to add this static piece of code, it should be something used in any Splice process (RegionServer, OlapServer, SparkExecutor...)

Would it be better to have an explicit call for each type of server on their startup sequence?

**Comment by scottfines** [comment]
+1 I'm okay with it. It's not ideal, but I can't think of anyplace else that would be better.

**Comment by jeffcunningham** [comment]
+1

**Comment by jleach4** [comment]
+1

**Pull request merged**
