### PR TITLE
DB-10371: cast CHAR_OCTET_LENGTH column of getColumn metadata query to int

### PR DESCRIPTION
**Pull request by jyuanca**

### CODE REVIEW

**Comment by jyuanca** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Review by bklo94 — APPROVED** [review]

**Review by dgomezferro — APPROVED** [review]

**Comment by jyuanca** [comment]
See https://splicemachine.atlassian.net/browse/DB-10371 for details

**Review by arnaud-splice — APPROVED** [review]

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1629/

**Review by carolp-503 — APPROVED** [review]
+1

**Pull request merged**
