### PR TITLE
DB-10439 Improve no stats report from explain statement

### PR DESCRIPTION
**Pull request by ascend1**
## Short Description
This change fixes an issue in explain statement output that missing statistics objects may have duplicates and inconsistent names due to aliases.

## Long Description
The issue is mainly due to `FromBaseTable.getExposedTable()` method. It returns alias as the table name if a table has an alias.

The fix is to call `FromBaseTable.getTableDescriptor().getQualifiedName()` instead. This guarantees to use always the original table name with correct spelling.

Note that there is also a method `FromBaseTable.getOrigTableName()` which is not sufficient in this case because the `origTableName` field could have `schemaName == null` and code in `isTransitionTable()` in `CreateTriggerNode.java` relies on that...

## How to test
Setup:
```
create table if not exists t1 (a int, b int, c int);
create table if not exists t2 (a int, b int, c int);
create table if not exists t3 (a int, b int, c int);
```

Query:
```
explain
select *
from t1
         inner join t2 as aliast2 on (aliast2.c = t1.b)
where t1.b is null
  and aliast2.c = 0;
```

Before this fix:
```
Table statistics are missing or skipped for the following tables:
SPLICE.T1, ALIAST2
Column statistics are missing or skipped for the following columns:
ALIAST2.C, SPLICE.T2.C, SPLICE.T1.B
```

After this fix:
```
Table statistics are missing or skipped for the following tables:
"SPLICE"."T1", "SPLICE"."T2"
Column statistics are missing or skipped for the following columns:
SPLICE.T2.C, SPLICE.T1.B
```

### CODE REVIEW

**Comment by ascend1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by cloudspliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/3179/

**Comment by ascend1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by cloudspliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/3183/

**Review by msirek — APPROVED** [review]

**Comment by ascend1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by cloudspliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/3196/

**Review by jyuanca — APPROVED** [review]

**Comment by msirek** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by cloudspliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
