### PR TITLE
SPLICE-1991: Add info to Spark UI for Compaction jobs to indicate presence of Reference Files

### PR DESCRIPTION
**Pull request by stpabhi**

### CODE REVIEW

**Comment by stpabhi** [comment]
@jleach4 @jyuanca please review

**Comment by wtang16** [comment]
@stpabhi We'll need 2.5/2.6 code shipment too.

**Comment by jyuanca** [comment]
@stpabhi Please also port the fix to other versions of habse(1.1.2, 1.1.2.2.5,etc)

**Comment by stpabhi** [comment]
@jyuanca ported to hbase 1.1.0, 1.1.2 and 1.1.2.2.5

**Pull request merged**
