### PR TITLE
DB-11073 Serialize current schema in ActivationHolder 

### PR DESCRIPTION
**Pull request by arnaud-splice**

### CODE REVIEW

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Review by msirek — APPROVED** [review]

**Review by dgomezferro — APPROVED** [review]

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by arnaud-splice** [comment]
@dgomezferro, @jyuanca  Do you think we need to do something specific regarding upgrades? The serialization of ActivationHolder will change with this PR

**Review by hatyo — APPROVED** [review]
LGTM 👍

**Review by carolp-503 — APPROVED** [review]
+1

**Comment by dgomezferro** [comment]
@arnaud-splice not for now, the serialization is only used at runtime. We might need to address it for online upgrade though.

**Pull request merged**
