### PR TITLE
DB-8168 Decode args from Sqlca

### PR DESCRIPTION
**Pull request by hatyo**

### CODE REVIEW

**Comment by hatyo** [comment]
I am reviving this change from Mark, I tested it and it works as expected.

**Comment by jyuanca** [comment]
If possible, add a test case.

**Comment by hatyo** [comment]
Hi Jun,
please check [my comment](https://splicemachine.atlassian.net/browse/DB-8168?focusedCommentId=67832) on the respective ticket, I wasn't actually able to reproduce this issue with Yi's example and other queries I tried.

**Comment by hatyo** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1005/

**Comment by hatyo** [comment]
`Spliceengine Branch`  build job failed due to intermittent failure in a test, see `DB-9818` for more information.

**Comment by hatyo** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1033/

**Comment by hatyo** [comment]
This time, it failed because of yet another sporadically failing test `DB-9786`.

**Pull request merged**
