### PR TITLE
DB-9425 Reduce scale of a result decimal type when necessary (3.0)

### PR DESCRIPTION
**Pull request by ascend1**

### CODE REVIEW

**Comment by martinrupp** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by martinrupp** [comment]
please cherry-pick 
- DB-9425 Fix division result type precision/scale
- DB-9425 Make comments correct

to here from https://github.com/splicemachine/spliceengine/pull/3892/commits as well

**Comment by ascend1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1217/

**Pull request merged**
