### PR TITLE
DB-11089 Fix NPE in SQLChar.setWidth if warning occurs without resultset 

### PR DESCRIPTION
**Pull request by arnaud-splice**

### CODE REVIEW

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by dgomezferro — APPROVED** [review]
Change looks good to avoid the NPE. Arnaud is going to create a JIRA to fix the places where we are missing the activation or the ResultSet so that we don't skip attaching the Warning to it.

**Review by ipraznik-splice — APPROVED** [review]

**Comment by arnaud-splice** [comment]
> Change looks good to avoid the NPE. Arnaud is going to create a JIRA to fix the places where we are missing the activation or the ResultSet so that we don't skip attaching the Warning to it.

Tracked by DB-11106

**Review by carolp-503 — APPROVED** [review]
+1

**Pull request merged**
