### PR TITLE
DB-12352 Fix auto view refreshing mode for view on top of view (3.1)

### PR DESCRIPTION
**Pull request by ascend1**
See https://github.com/splicemachine/spliceengine/pull/5683.

### CODE REVIEW

**Comment by ascend1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by cloudspliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/3369/

**Comment by bklo94** [comment]
jenkins please test branch @cdh6.3.0

**Review by carolp-503 — APPROVED** [review]
Approved for 3.1

**Comment by cloudspliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/3371/

**Pull request merged**
