### PR TITLE
DB-7854 Deadlock in EmbedPreparedStatement.getMetaData() (2.7)

### PR DESCRIPTION
**Pull request by OlegMazurov**
Refactor to avoid an endless loop in a critical section.

### CODE REVIEW

**Comment by OlegMazurov** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST FAILED

**Comment by OlegMazurov** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
