### PR TITLE
DB-8792 Store oldest active transaction in each Region Server

### PR DESCRIPTION
**Pull request by arnaud-splice**

### CODE REVIEW

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST FAILED

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST FAILED

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by OlegMazurov** [comment]
Will there be a PR for branch-3.0?

**Comment by arnaud-splice** [comment]
> com.splicemachine.si.data.hbase.coprocessor.RegionServerEndpoint was renamed to com.splicemachine.si.data.hbase.coprocessor.SpliceRSRpcService by DB-8823. Please resolve the conflict before merging.

Done through the merge to master of the underlying PR.

**Comment by arnaud-splice** [comment]
> Will there be a PR for branch-3.0?

Absolutely. Pushing them now.

**Pull request merged**
