### PR TITLE
DB-11341 Fix {OrderBy,Union}Node.printExplainInformation 

### PR DESCRIPTION
**Pull request by arnaud-splice**

### CODE REVIEW

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2396/

**Review by jyuanca — CHANGES_REQUESTED** [review]
Add an IT

**Review by dgomezferro — COMMENTED** [review]
Change looks good, but I'd also add an IT

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by arnaud-splice** [comment]
> Add an IT

Done

**Review by dgomezferro — APPROVED** [review]
Thanks for the IT!

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by jyuanca — APPROVED** [review]

**Review by carolp-503 — APPROVED** [review]
+1

**Pull request merged**
