### PR TITLE
Splice-2338 Spurious column name in error message when querying parquet external tables

### PR DESCRIPTION
**Pull request by ngpham**
Please review only the last commit. Others are just merge and cleanup.

### CODE REVIEW

**Comment by ngpham** [comment]
jenkins please test branch @cdh5.14.0

**Comment by spliceci** [comment]
TEST FAILED

**Comment by ngpham** [comment]
jenkins please test branch @cdh5.14.0

**Comment by spliceci** [comment]
TEST FAILED

**Comment by ngpham** [comment]
jenkins please test branch @cdh5.14.0

**Comment by spliceci** [comment]
TEST FAILED

**Comment by ngpham** [comment]
jenkins please test branch @cdh5.14.0

**Comment by spliceci** [comment]
TEST FAILED

**Comment by ngpham** [comment]
jenkins please test branch @cdh5.14.0

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by jaceklaskowski** [comment]
Please re-create the PR with just the change to review and merge. Thanks.

**Pull request closed without merging**
