### PR TITLE
DB-10555 Support multi-column (not-)in-subquery

### PR DESCRIPTION
**Pull request by ascend1**

### CODE REVIEW

**Comment by ascend1** [comment]
jenkins please test branch @cdh6.3.0

**Review by arnaud-splice — CHANGES_REQUESTED** [review]
Great change! One small request: can you add a test with a table that does not have matching columns? For example, instead of (1, 10) (2,20) (3,30)… have something like (1, 10) (1, 20) (2,20)… 
That would catch potential bugs where we'd compare only the first column of the subquery.

**Review by msirek — APPROVED** [review]
Looks good.  There can be issues with NOT IN subqueries with nulls.  It would be good to add some test cases using a nullable column in one of the NOT IN columns and a non-nullable column in the other, and then test that the answer is the same when the order of the columns is swapped.  Use nulls in the data too.

**Comment by ascend1** [comment]
> Great change! One small request: can you add a test with a table that does not have matching columns? For example, instead of (1, 10) (2,20) (3,30)… have something like (1, 10) (1, 20) (2,20)…
> That would catch potential bugs where we'd compare only the first column of the subquery.

Sure, I add one such test in the latest commit.

**Comment by ascend1** [comment]
> Looks good. There can be issues with NOT IN subqueries with nulls. It would be good to add some test cases using a nullable column in one of the NOT IN columns and a non-nullable column in the other, and then test that the answer is the same when the order of the columns is swapped. Use nulls in the data too.

Yes, I add one test to cover this case in the latest commit.

**Comment by ascend1** [comment]
jenkins please test branch @cdh6.3.0

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by arnaud-splice — APPROVED** [review]

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1916/

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
