### PR TITLE
DB-7743 Remove dot from classifiers

### PR DESCRIPTION
**Pull request by bklo94**
Tested with a new job at (Core has the last build aborted since I version bumped and it watches the branch)
http://stl-colo-vm-jm.splicemachine.local:8080/view/miscellaneous/job/DB-7743/

The metadata looks to be working (ignore the ones with with the smashed together classifiers since I used that for initial testing).
http://repository.splicemachine.com/nexus/content/repositories/snapshots/com/splicemachine/splice_spark/0.0.0.1-SNAPSHOT/maven-metadata.xml

There is an associated spliceengine-ee branch.

### CODE REVIEW

**Comment by bklo94** [comment]
jenkins please test branch @cdh5.12.2

**Comment by bklo94** [comment]
jenkins please test branch @cdh5_12_2

**Comment by bklo94** [comment]
jenkins please test branch @cdh5_12_2

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by bklo94** [comment]
jenkins please test branch @cdh5_12_2

**Comment by bklo94** [comment]
jenkins please test branch @cdh5_12_2

**Comment by bklo94** [comment]
jenkins please test branch @cdh5_12_2

**Comment by bklo94** [comment]
jenkins please test branch @cdh5_12_

**Comment by bklo94** [comment]
jenkins please test branch @cdh5_12_2

**Comment by bklo94** [comment]
jenkins please test branch @cdh5_12_2

**Comment by bklo94** [comment]
jenkins please test branch @cdh5_12_2

**Comment by bklo94** [comment]
jenkins please test branch @cdh5_12_@

**Comment by bklo94** [comment]
jenkins please test branch @cdh5_12_2

**Comment by bklo94** [comment]
jenkins please test branch @cdh5_12_2

**Comment by bklo94** [comment]
jenkins please test branch @cdh5_12_2

**Comment by bklo94** [comment]
jenkins please test branch @cdh5_12_2

**Comment by bklo94** [comment]
jenkins please test branch @cdh5_12_2

**Comment by bklo94** [comment]
jenkins please test branch @cdh5_12_2

**Comment by bklo94** [comment]
jenkins please test branch @cdh5_12_2

**Comment by bklo94** [comment]
jenkins please retest branch @cdh5.12.2

**Comment by msirek** [comment]
@bklo94 So, with this change, we can no longer build with a target version with period as the separator? 
 e.g.  mvn install -Pcore,cdh5.12.2
it would have to be: mvn install -Pcore,cdh5_12_2  ?

**Comment by bklo94** [comment]
@msirek Correct, no need to edit the configuration. Though it hasn't been fully tested, so I summoned the splice-PR branch job again.

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by msirek** [comment]
Is there no way to allow the target to still have periods?  cdh5.12.2 looks a lot nicer as a version on the command line than cdh5_12_2.  What if the <id> under the <profile> still has periods, but the classifier has underscores?  Would this work?  I don't know if anyone else has an opinion on this.

**Comment by bklo94** [comment]
Ah I guess my comment wasn't too clear. I just put in the last commit to let the targets still be cdh5.12.2 (with dots). The main difference will only be the naming of the jars will have cdh5_12_2 instead of having dots.

**Comment by msirek** [comment]
OK, got it.  Does your latest commit address @dgomezferro's comments?  Just wondering if this PR is finalized now, and ready for others to review.

**Comment by bklo94** [comment]
Yeah. I believe I addressed @dgomezferro's comments. There's a Jenkins job that should be alright since it's passed a couple of times. 
jenkins please retest branch @cdh5.12.2

**Comment by liprais** [comment]
so in general we build using -Pcdh5.12.2 and in dependencies we use <classifier>cdh5_12_2</classifier>?

**Comment by spliceci** [comment]
TEST FAILED - Yeah. I believe I addressed @dgomezferro's comments. There's a Jenkins job that should be alright since it's passed a couple of times. \r\njenkins please retest branch @cdh5.12.2\r\n\r\n

**Comment by spliceci** [comment]
TEST FAILED - TEST FAILED - Yeah. I believe I addressed @dgomezferro's comments. There's a Jenkins job that should be alright since it's passed a couple of times. \r\njenkins please retest branch @cdh5.12.2\r\n\r\n\n \n

**Comment by spliceci** [comment]
TEST FAILED - TEST FAILED - TEST FAILED - Yeah. I believe I addressed @dgomezferro's comments. There's a Jenkins job that should be alright since it's passed a couple of times. \r\njenkins please retest branch @cdh5.12.2\r\n\r\n\n \n\n \n

**Comment by spliceci** [comment]
TEST FAILED - TEST FAILED - TEST FAILED - TEST FAILED - Yeah. I believe I addressed @dgomezferro's comments. There's a Jenkins job that should be alright since it's passed a couple of times. \r\njenkins please retest branch @cdh5.12.2\r\n\r\n\n \n\n \n\n \n

**Pull request closed without merging**
