### PR TITLE
SPLICE-828 External Table Implementation

### PR DESCRIPTION
**Pull request by jleach4**
External Table Implementation for Splice Machine.  
Allows for...
- Creating External Parquet Tables
- Creating External ORC Files
- Creating External Flat File Table
- Allows for pinning tables in memory from either HBase or External Tables
- Integrated with the prior commit Splice-159.  We can now read columnar files from S3 and Azure Blob while also being able to pin their data into Spark Memory.

Places where I missed the mark and came up short...

Splice-1118 External Tables: TEXTFILE type does not follow the structure of imports
Splice-1119 External Tables: Optional Compression for writing Parquet, ORC, and Textfiles.
Splice-1120 External Tables: Allow Pinning of an Entire Schema into memory
Splice-1121 External Tables: Create statistics tests for external tables (Parquet, Orc, and Textfiles)
Splice-1122 Evaluate System calls now that we have External Tables

### CODE REVIEW

**Comment by jleach4** [comment]
Here is the syntax sheet for External Tables.

		```
	[ <LEFT_PAREN> resultColumns = tableColumnList() <RIGHT_PAREN> ]
						[<COMMA>]
                        [ <PARTITIONED> <BY> <LEFT_PAREN> partitionedResultColumns = tableColumnList() <RIGHT_PAREN> ]
                        [<COMMA>]
                        [ <ROW> <FORMAT> <DELIMITED>
                            [ <FIELDS> <TERMINATED> <BY> { terminationChar=literal(); }  [
                            [<COMMA>]
                            <ESCAPED> <BY> { escapedByChar=literal(); } ] ]
                            [<COMMA>]
                            [ <LINES> <TERMINATED> <BY> { linesTerminatedByChar=literal(); } ]
                        ]
            			[<COMMA>]
                        [<STORED> <AS> storageFormat = storedAs() ]
            			[<COMMA>]
                        [<LOCATION> {location = literal();}]
```

**Comment by jleach4** [comment]
Syntax for pinning

```
create pin table 'Foo';

drop pin 'Foo';
```

**Comment by jfilali** [comment]
+1

**Comment by graziergeek** [comment]
Wow, nice!

**Pull request merged**
