### PR TITLE
DB-11267 add SYSVW.SYSTRIGGERSVIEW

### PR DESCRIPTION
**Pull request by martinrupp**
## Short Description
- DB-11267 added SYSVW.SYSTRIGGERSVIEW
- DB-11267 added SYSVW.SYSALIASESVIEW
- DB-11688 fix SYSINDEXCOLUSE in SYSALIASES

## Long Description
added SYSVW.SYSTRIGGERSVIEW and SYSVW.SYSALIASESVIEW since SYS.SYSTRIGGERS and SYS.SYSALIASES can not be directly queried over JDBC due to marshal problems.

### test SYSINDEXCOLUSE in SYSALIASES
Execute this query without error (with sqlshell from spliceengine)
```
select * from SYS.SYSALIASES WHERE ALIAS = 'SYSINDEXCOLUSE';
```

### test SYSALIASESVIEW
Execute this query without error (with ext. sqlshell)
```
select * from SYSVW.SYSALIASESVIEW WHERE ALIAS = 'SYSINDEXCOLUSE';
```

### test SYSTRIGGERSVIEW
make sure `SYSVW.SYSTRIGGERSVIEW` would return at least one line by creating an example table+trigger:
```
CREATE TABLE T1(A VARCHAR(5), B VARCHAR(5));
CREATE TRIGGER mytrigger BEFORE INSERT
   ON t1 REFERENCING NEW AS N
   FOR EACH ROW
   BEGIN ATOMIC
      SET N.a = 'hello', N.b = 'goodbye';
   END;
```
Now with this PR, the following should return a valid result and no error (with ext. sqlshell).
```
SELECT * FROM SYSVW.SYSTRIGGERSVIEW;
```

### CODE REVIEW

**Comment by martinrupp** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2646/

**Review by jyuanca — CHANGES_REQUESTED** [review]
Need upgrade scripts

**Comment by martinrupp** [comment]
> Need upgrade scripts

i was wondering if https://github.com/splicemachine/spliceengine/pull/5282 would get merged then we wouldn't need upgrade scripts for views

**Comment by martinrupp** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by msirek** [comment]
jenkins please test branch @cdh6.3.0

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2665/

**Comment by msirek** [comment]
jenkins please test branch @cdh6.3.0

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by msirek — APPROVED** [review]

**Review by jyuanca — APPROVED** [review]

**Review by carolp-503 — APPROVED** [review]
+1

**Pull request merged**
