### PR TITLE
Add artifact stage

### PR DESCRIPTION
**Pull request by bklo94**
## Short Description
Add an artifact check stage in order for a quick smoke test of whether all the versions can be built from a PR or not. If the artifacts can't be built, then the PR should be rejected.

## Long Description
This PR adds an additional stage to check if artifacts can be built or not. It runs the initial build check and then the spotbug stages in a single node. Then it dynamically generates the new stages depending on the branch. There is some duplicate needed since the new node cannot inherit the environment variables from the pipeline, so it needs to check the correct source_branch again along with doing another checkout. Once the spotbugs stage is completed, the artifact build stage is all run in parllel, so the normal case of dbaas3,dbaas3.1,cdh6.3.0,hdp3.1.0, and hdp3.1.5 are all run at the same time once triggered.

## How to test
Hooked up to the spotbugs pipeline, so any commits will trigger a build.

### CODE REVIEW

**Comment by bklo94** [comment]
jenkins please test branch @mem

**Comment by cloudspliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/3218/

**Comment by bklo94** [comment]
jenkins please test branch @mem

**Comment by cloudspliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/3219/

**Comment by bklo94** [comment]
jenkins please test branch @mem

**Comment by cloudspliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/3221/

**Comment by cloudspliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/3223/

**Review by arnaud-splice — APPROVED** [review]

**Review by ipraznik-splice — APPROVED** [review]

**Review by carolp-503 — APPROVED** [review]
+1

**Pull request merged**
