### PR TITLE
DB-9844 Spark 3.0 Remove org.spark_project.* references (ver 2., shaded )

### PR DESCRIPTION
**Pull request by ipraznik-splice**

### CODE REVIEW

**Comment by ipraznik-splice** [comment]
> @ipraznik-splice After build splice, where can find the shaded jar?

the relocation is done with parameter <shadedArtifactAttached>false</shadedArtifactAttached>, splice.com.google.common.* is in the built utilities-*.jar, utilities-3.1.0.1970-SNAPSHOT.jar:

com/splicemachine/*
com/carrotsearch/*
org/xerial/*
**splice/com/google/common/***
org/apache/commons/lang3/*

**Comment by ipraznik-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1390/

**Comment by ipraznik-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1391/

**Comment by ipraznik-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
