### PR TITLE
SPLICE-730 Cleaning up BasicDatabase operations, added a few java doc…

### PR DESCRIPTION
**Pull request by jleach4**
Basic Database Code Cleanup of dead methods, javadoc additions, and code cleanup.

### CODE REVIEW

**Comment by jfilali** [comment]
+1

**Comment by dgomezferro** [comment]
+1

**Comment by jyuanca** [comment]
+1

**Comment by jyuanca** [comment]
This caused a build failure because some classes that are being used by backup are deleted. I've reverted changes.

**Pull request merged**
