### PR TITLE
DB-9979 reduce the amount of data dictionary calls for row triggers under spark execution

### PR DESCRIPTION
**Pull request by yxia92**

### CODE REVIEW

**Comment by yxia92** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1563/

**Comment by yxia92** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Review by dgomezferro — APPROVED** [review]

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1564/

**Review by martinrupp — APPROVED** [review]
lgtm

**Review by arnaud-splice — APPROVED** [review]

**Review by jyuanca — COMMENTED** [review]
why triggers are always run on spark if data in inserted from NSDS?

**Comment by yxia92** [comment]
@jyuanca For the insert statement from NSDS, the insert itself runs in spark, but for the statements triggered from the row triggers as a result of the insert, they actually run in control processors.

**Review by jyuanca — APPROVED** [review]
why triggers are always run on spark if data in inserted from NSDS?

**Review by carolp-503 — APPROVED** [review]
+1

**Comment by yxia92** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
