### PR TITLE
DB-9596 AuthorizationIT fails without enterprise Manager in open sour…

### PR DESCRIPTION
**Pull request by ipraznik-splice**
…ce. Call not needed any more.

### CODE REVIEW

**Comment by OlegMazurov** [comment]
Have you tested if AuthorizationIT passes WITH the enterprise Manager enabled?
When executed during ITs, AuthorizationIT may find the database in both states.
I suspect the call to explicitly disable enterprise features was added to fix test instability under the circumstances.

**Comment by ipraznik-splice** [comment]
> Have you tested if AuthorizationIT passes WITH the enterprise Manager enabled?
> When executed during ITs, AuthorizationIT may find the database in both states.
> I suspect the call to explicitly disable enterprise features was added to fix test instability under the circumstances.

I have not tested with enterprise Manager enabled. I've checked other ITs and have not found any place, where it's enabled, but I did a mistake, as I checked only splicemachine without splicemachine-ee. In the case, when enterprise feature is enabled in another IT, one test testPermissionOnColumn will be failed, that relies on enterprise Manager disabled. I've added the disable code back with the handling of Manager not initialised.

Thank you.

**Comment by ipraznik-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED

**Comment by ipraznik-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
