### PR TITLE
DB-9967 DB-10015 improvements to sqlshell's spool.

### PR DESCRIPTION
**Pull request by hatyo**
Addresses both subtasks DB-9967 and DB-10015

### CODE REVIEW

**Review by dgomezferro — APPROVED** [review]

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1445/

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
