### PR TITLE
 DB-7794 Remove spark_avro from platform_it

### PR DESCRIPTION
**Pull request by bklo94**
Move to hbase_sql, ran 1384,1385 spliceengine-branch builds

### CODE REVIEW

**Comment by bklo94** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST FAILED

**Comment by bklo94** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST FAILED

**Comment by bklo94** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by spliceci** [comment]
TEST FAILED

**Comment by bklo94** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
