### PR TITLE
DB-10024 support drop schema cascade

### PR DESCRIPTION
**Pull request by yxia92**

### CODE REVIEW

**Review by hatyo — APPROVED** [review]
Great work!

**Review by martinrupp — APPROVED** [review]

**Review by ascend1 — APPROVED** [review]

**Review by arnaud-splice — APPROVED** [review]

**Review by dgomezferro — CHANGES_REQUESTED** [review]
A self-referencing FK causes an endless loop:
```
create schema test;
create table test.test(i int primary key, j int, constraint fk  foreign key(j) references test.test(i));
drop schema test cascade ;
```

**Comment by yxia92** [comment]
Thanks @dgomezferro for catching this problem! I've made a commit to address this issue.

**Comment by yxia92** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1689/

**Comment by yxia92** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Review by dgomezferro — APPROVED** [review]

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by carolp-503 — APPROVED** [review]
+1

**Pull request merged**
