### PR TITLE
SPLICE-1192 Removing restrictive checks for prospect

### PR DESCRIPTION
**Pull request by jleach4**
Splice Machine prospect would like to remove restrictions on the column transformation on top of a union.

### CODE REVIEW

**Comment by dgomezferro** [comment]
What was the example that required this change? I think removing the check completely is wrong, we might want to make it less restrictive though.

What's the reasoning behind allowing the query in the added test case?

**Comment by jleach4** [comment]
The rationale for this is that a splice user would like the normal type conversion to occur vs. a more restrictive type structure for unions.  The union type conversion is much more restrictive than type conversion for example for an insert.

**Comment by dgomezferro** [comment]
I don't think we should be relaxing type safety so much for unions, it would be almost worthless. Isn't there any other option casting one side of the union to the other type, for example? What do other databases implement? 

I'm worried about inconsistencies if we allow this. For instance, in this case:

`create table a (i int);
create table b (i varchar(20));`

This statement 
`insert into a select * from b;`
would fail, but this one
`insert into a select * from a union all select * from b;`
would work (only if all values in b are integers...).

**Comment by scottfines** [comment]
I'm inclined to agree with Daniel on this: Do we know the reason why Derby chose to be more restrictive here? I have a sinking feeling that it's because of relational algebra/type system constraints, and we'll be hating ourselves for opening up the system.

**Comment by jfilali** [comment]
Should we close that pull request for now ? 
@jleach4

**Pull request closed without merging**
