### PR TITLE
DB-11891 Refactor upgrade scripts to add and populate new columns

### PR DESCRIPTION
**Pull request by arnaud-splice**
## Short Description

Refactor upgrade code to add and populate new columns to system tables

## Long Description

This is an extract of code from DB-10193 that I'd like to make available before DB-10193 is merged.

### CODE REVIEW

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2773/

**Comment by arnaud-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by martinrupp — APPROVED** [review]

**Review by ipraznik-splice — APPROVED** [review]

**Pull request merged**
