### PR TITLE
SPLICE-968 add groupingid column for rollup operation and fix wrong r…

### PR DESCRIPTION
**Pull request by yxia92**
…esult

SPLICE-968 support grouping() function for OLAP operation.
SPLICE-968 make grouping function working with window functions

This PR provides support for GROUPING function. For details of the solution, please see [SPLICE-968](https://splice.atlassian.net/browse/SPLICE-968)

### CODE REVIEW

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Comment by yxia92** [comment]
Add a commit to tighten the semantic check for window functions.

**Comment by yxia92** [comment]
jenkins please test branch @cdh5.12.2

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
