### PR TITLE
DB-9669 avoid pushing outer join condition to left table, and avoid u…

### PR DESCRIPTION
**Pull request by yxia92**
…sing outer join condition to eliminate order by columns.

### CODE REVIEW

**Comment by yxia92** [comment]
jenkins please test branch @cdh5.12.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED

**Comment by yxia92** [comment]
jenkins please test branch @cdh5.12.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Pull request merged**
