### PR TITLE
DB-11603 Properly separate privileges drop when dropping roles

### PR DESCRIPTION
**Pull request by arnaud-splice**
## Short Description
DataDictionary.dropAllPermsByGrantee should filter grantees per databaseId

## Long Description
In a multidatabase environment, only checking for grantees is not enough anymore when attempting to drop privileges. We should filter privileges by databaseId before dropping

## How to test
*splicedb2*:
```
CREATE SCHEMA S; CREATE ROLE FOO; GRANT ALL PRIVILEGES ON SCHEMA S TO FOO;
select * from sysvw.sysschemapermsview;
SCHEMAPER&|GRANTEE   |GRANTOR   |SCHEMAID  |&|&|&|&|&|&|MOD&|ACC&|SCHEMANAME
60430428-&|FOO       |SPLICE    |a23943da-&|y|y|y|y|y|y|y   |y   |S
```

*splicedb*:
```
CREATE SCHEMA S; CREATE ROLE FOO; GRANT ALL PRIVILEGES ON SCHEMA S TO FOO;
select * from sysvw.sysschemapermsview;
SCHEMAPER&|GRANTEE   |GRANTOR   |SCHEMAID  |&|&|&|&|&|&|MOD&|ACC&|SCHEMANAME
97fc8455-&|FOO       |SPLICE    |bbe583e4-&|y|y|y|y|y|y|y   |y   |S
```

Now drop one role FOO:

*splicedb*:
```
DROP ROLE FOO;
select * from sysvw.sysschemapermsview;
SCHEMAPER&|GRANTEE   |GRANTOR   |SCHEMAID  |&|&|&|&|&|&|MOD&|ACC&|SCHEMANAME
```

The privileges on *splicedb2* should not be affected:

*splicedb2*:
```
select * from sysvw.sysschemapermsview;
SCHEMAPER&|GRANTEE   |GRANTOR   |SCHEMAID  |&|&|&|&|&|&|MOD&|ACC&|SCHEMANAME
60430428-&|FOO       |SPLICE    |a23943da-&|y|y|y|y|y|y|y   |y   |S
```

### CODE REVIEW

**Comment by msirek** [comment]
@arnaud-splice  This PR is showing other commits like those from DB-10410.  Is there a way to hide those to make this easier to review?  Maybe cherry-pick the commits to a new branch?

**Comment by arnaud-splice** [comment]
> @arnaud-splice This PR is showing other commits like those from DB-10410. Is there a way to hide those to make this easier to review? Maybe cherry-pick the commits to a new branch?

Thanks for the reminder, I had forgotten to redirect that PR to DB-10193
You should now see a diff of +86 -20 lines if you filter out whitespaces

**Review by martinrupp — APPROVED** [review]

**Review by msirek — APPROVED** [review]
+1

**Review by carolp-503 — COMMENTED** [review]
+1

**Pull request merged**
