### PR TITLE
DB-12140 Fix index on expressions logic for UnaryDateTimestampOperatorNode (3.1)

### PR DESCRIPTION
**Pull request by ascend1**
See https://github.com/splicemachine/spliceengine/pull/5535.

### CODE REVIEW

**Comment by ascend1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by cloudspliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/3016/

**Comment by ascend1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by cloudspliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/3022/

**Comment by ascend1** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by cloudspliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/3029/

**Review by carolp-503 — APPROVED** [review]
Approved for 3.1

**Comment by ascend1** [comment]
Strange that `testSchemaBackupRestore` passes locally but seems to fail always on Jenkins. I've asked for help from @jyuanca .

**Pull request merged**
