### PR TITLE
DB-11865 + DB-10579 backport (3.1)

### PR DESCRIPTION
**Pull request by msirek**
Backport the following Jiras required by DB-11580:
DB-11865 Enable native spark broadcast join with non-equijoin predicates
DB-10579 Use truly nested transactions for triggers.

### CODE REVIEW

**Comment by msirek** [comment]
jenkins please test branch @cdh6.3.0

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2908/

**Comment by msirek** [comment]
jenkins please test branch @cdh6.3.0

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by carolp-503 — APPROVED** [review]
Approved for 3.1

**Pull request merged**
