### PR TITLE
WIP DB-10508 IntelliJ IDEA does not handle shaded packages properly

### PR DESCRIPTION
**Pull request by ipraznik-splice**

### CODE REVIEW

**Review by jyuanca — APPROVED** [review]

**Review by msirek — APPROVED** [review]
+1

**Review by carolp-503 — APPROVED** [review]
+1

**Comment by ipraznik-splice** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1848/

**Review by bklo94 — APPROVED** [review]

**Comment by hatyo** [comment]
Great work, makes life easier, as discussed maybe we should check it with mem-profile as well and also include the aws shaded JAR.

**Comment by dgomezferro** [comment]
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2154/

**Pull request closed without merging**
