### PR TITLE
DB-11405 Fix 'Unable to generate code' error with multiple subqueries

### PR DESCRIPTION
**Pull request by msirek**
### Description
DB-10774 modified the binding code to only add a SubqueryNode once to a subqueryList in an effort to bind the subquery only once in a given subtree.  The problem is there could be different subtrees that maintain their own subqueryList and they reference that SubqueryNode as well.  The SubqueryNode should be added to those other subqueryLists as well, but since the new flag thisSubqueryAddedToSubqueryList is now false, we fail to do so.

example query:

> insert into B values (
>     nullif(
>         case when
>             EXISTS (select C1 from C where EXISTS (select A1 from A))
>         then 14 end,
>         4)
> );

ERROR 42Z50: INTERNAL ERROR: Unable to generate code for
com.splicemachine.db.impl.sql.compile.SelectNode@45eb0df

### Fix
The fix is to add the SubqueryNode to subqueryList, but only if it is not already present in the list.  The thisSubqueryAddedToSubqueryList flag is removed.

### CODE REVIEW

**Comment by msirek** [comment]
jenkins please test branch@cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2441/

**Review by arnaud-splice — APPROVED** [review]

**Review by jyuanca — APPROVED** [review]

**Comment by msirek** [comment]
jenkins please test branch@cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2442/

**Comment by msirek** [comment]
jenkins please test branch@cdh6.3.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST SUCCEEDED +1

**Review by hatyo — APPROVED** [review]

**Review by ascend1 — APPROVED** [review]

**Review by carolp-503 — APPROVED** [review]
+1

**Pull request merged**
