### PR TITLE
DB-8363 Null Serialization in db-engine / NSDS Insert Null ITs (2.8)

### PR DESCRIPTION
**Pull request by jpanko1**

### CODE REVIEW

**Comment by martinrupp** [comment]
jenkins please test branch @cdh5.12.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1209/

**Comment by jpanko1** [comment]
jenkins please test branch @cdh5.12.0,skipTestsLongerThan2Minutes

**Comment by spliceci** [comment]
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1211/

**Pull request merged**
